// Generated by pscpp compiler

#ifndef Data_Ordering_H
#define Data_Ordering_H

#include "purescript.h"

namespace Data_Ordering {

using namespace purescript;

auto LT() -> const boxed&;
auto GT() -> const boxed&;
auto EQ() -> const boxed&;
auto showOrdering() -> boxed;
auto semigroupOrdering() -> boxed;
auto invert() -> const boxed&;
auto eqOrdering() -> boxed;

} // end namespace Data_Ordering

#endif // Data_Ordering_H

