// Generated by pscpp compiler

#ifndef Global_Unsafe_H
#define Global_Unsafe_H

#include "purescript.h"

namespace Global_Unsafe {

using namespace purescript;

auto unsafeStringify() -> const boxed&;
auto unsafeToFixed() -> const boxed&;
auto unsafeToExponential() -> const boxed&;
auto unsafeToPrecision() -> const boxed&;
auto unsafeDecodeURI() -> const boxed&;
auto unsafeEncodeURI() -> const boxed&;
auto unsafeDecodeURIComponent() -> const boxed&;
auto unsafeEncodeURIComponent() -> const boxed&;

} // end namespace Global_Unsafe

#endif // Global_Unsafe_H

