// Generated by pscpp compiler

#ifndef Data_String_NonEmpty_CodeUnits_H
#define Data_String_NonEmpty_CodeUnits_H

#include "purescript.h"

namespace Data_String_NonEmpty_CodeUnits {

using namespace purescript;

auto toNonEmptyString() -> boxed;
auto snoc() -> const boxed&;
auto singleton() -> boxed;
auto liftS() -> boxed;
auto takeWhile() -> const boxed&;
auto lastIndexOf_Prime_() -> const boxed&;
auto lastIndexOf() -> boxed;
auto indexOf_Prime_() -> const boxed&;
auto indexOf() -> boxed;
auto fromNonEmptyString() -> boxed;
auto length() -> boxed;
auto splitAt() -> const boxed&;
auto take() -> const boxed&;
auto takeRight() -> const boxed&;
auto toChar() -> boxed;
auto toCharArray() -> boxed;
auto toNonEmptyCharArray() -> boxed;
auto uncons() -> const boxed&;
auto fromFoldable1() -> const boxed&;
auto fromCharArray() -> const boxed&;
auto fromNonEmptyCharArray() -> boxed;
auto dropWhile() -> const boxed&;
auto dropRight() -> const boxed&;
auto drop() -> const boxed&;
auto countPrefix() -> boxed;
auto cons() -> const boxed&;
auto charAt() -> boxed;

} // end namespace Data_String_NonEmpty_CodeUnits

#endif // Data_String_NonEmpty_CodeUnits_H

