// Generated by pscpp compiler

#ifndef Data_Ord_Min_H
#define Data_Ord_Min_H

#include "purescript.h"

namespace Data_Ord_Min {

using namespace purescript;

auto Min() -> const boxed&;
auto showMin() -> const boxed&;
auto semigroupMin() -> const boxed&;
auto newtypeMin() -> boxed;
auto monoidMin() -> const boxed&;
auto eqMin() -> const boxed&;
auto ordMin() -> const boxed&;

} // end namespace Data_Ord_Min

#endif // Data_Ord_Min_H

