// Generated by pscpp compiler

#ifndef Main_H
#define Main_H

#include "purescript.h"

namespace Main {

using namespace purescript;

auto main() -> boxed;

} // end namespace Main

#endif // Main_H

