// Generated by pscpp compiler

#ifndef Data_Monoid_Alternate_H
#define Data_Monoid_Alternate_H

#include "purescript.h"

namespace Data_Monoid_Alternate {

using namespace purescript;

auto Alternate() -> const boxed&;
auto showAlternate() -> const boxed&;
auto semigroupAlternate() -> const boxed&;
auto plusAlternate() -> const boxed&;
auto ordAlternate() -> const boxed&;
auto ord1Alternate() -> const boxed&;
auto monoidAlternate() -> const boxed&;
auto monadAlternate() -> const boxed&;
auto functorAlternate() -> const boxed&;
auto extendAlternate() -> const boxed&;
auto eqAlternate() -> const boxed&;
auto eq1Alternate() -> const boxed&;
auto comonadAlternate() -> const boxed&;
auto boundedAlternate() -> const boxed&;
auto bindAlternate() -> const boxed&;
auto applyAlternate() -> const boxed&;
auto applicativeAlternate() -> const boxed&;
auto alternativeAlternate() -> const boxed&;
auto altAlternate() -> const boxed&;

} // end namespace Data_Monoid_Alternate

#endif // Data_Monoid_Alternate_H

