// Generated by pscpp compiler

#ifndef Data_Char_Unicode_H
#define Data_Char_Unicode_H

#include "purescript.h"

namespace Data_Char_Unicode {

using namespace purescript;

auto UppercaseLetter() -> const boxed&;
auto LowercaseLetter() -> const boxed&;
auto TitlecaseLetter() -> const boxed&;
auto ModifierLetter() -> const boxed&;
auto OtherLetter() -> const boxed&;
auto NonSpacingMark() -> const boxed&;
auto SpacingCombiningMark() -> const boxed&;
auto EnclosingMark() -> const boxed&;
auto DecimalNumber() -> const boxed&;
auto LetterNumber() -> const boxed&;
auto OtherNumber() -> const boxed&;
auto ConnectorPunctuation() -> const boxed&;
auto DashPunctuation() -> const boxed&;
auto OpenPunctuation() -> const boxed&;
auto ClosePunctuation() -> const boxed&;
auto InitialQuote() -> const boxed&;
auto FinalQuote() -> const boxed&;
auto OtherPunctuation() -> const boxed&;
auto MathSymbol() -> const boxed&;
auto CurrencySymbol() -> const boxed&;
auto ModifierSymbol() -> const boxed&;
auto OtherSymbol() -> const boxed&;
auto Space() -> const boxed&;
auto LineSeparator() -> const boxed&;
auto ParagraphSeparator() -> const boxed&;
auto Control() -> const boxed&;
auto Format() -> const boxed&;
auto Surrogate() -> const boxed&;
auto PrivateUse() -> const boxed&;
auto NotAssigned() -> const boxed&;
auto unicodeCatToGeneralCat() -> const boxed&;
auto toUpper() -> boxed;
auto toTitle() -> boxed;
auto toLower() -> boxed;
auto showGeneralCategory() -> boxed;
auto isUpper() -> boxed;
auto isSpace() -> const boxed&;
auto isPrint() -> boxed;
auto isOctDigit() -> const boxed&;
auto isLower() -> boxed;
auto isLatin1() -> const boxed&;
auto isDigit() -> const boxed&;
auto isHexDigit() -> const boxed&;
auto isControl() -> boxed;
auto isAsciiUpper() -> const boxed&;
auto isAsciiLower() -> const boxed&;
auto isAscii() -> const boxed&;
auto isAlphaNum() -> boxed;
auto isAlpha() -> boxed;
auto generalCategory() -> boxed;
auto isLetter() -> const boxed&;
auto isMark() -> const boxed&;
auto isNumber() -> const boxed&;
auto isPunctuation() -> const boxed&;
auto isSeparator() -> const boxed&;
auto isSymbol() -> const boxed&;
auto generalCatToUnicodeCat() -> const boxed&;
auto generalCatToInt() -> const boxed&;
auto eqGeneralCategory() -> boxed;
auto ordGeneralCategory() -> boxed;
auto digitToInt() -> const boxed&;
auto boundedGeneralCategory() -> boxed;
auto withCharCode() -> const boxed&;

} // end namespace Data_Char_Unicode

#endif // Data_Char_Unicode_H

