// Generated by pscpp compiler

#ifndef Partial_Unsafe_H
#define Partial_Unsafe_H

#include "purescript.h"

namespace Partial_Unsafe {

using namespace purescript;

auto unsafePartialBecause() -> const boxed&;
auto unsafeCrashWith() -> const boxed&;
auto unsafePartial() -> const boxed&;

} // end namespace Partial_Unsafe

#endif // Partial_Unsafe_H

