// Generated by pscpp compiler

#ifndef Control_Comonad_Traced_Class_H
#define Control_Comonad_Traced_Class_H

#include "purescript.h"

namespace Control_Comonad_Traced_Class {

using namespace purescript;

auto ComonadTraced() -> const boxed&;
auto track() -> const boxed&;
auto tracks() -> const boxed&;
auto listens() -> const boxed&;
auto listen() -> const boxed&;
auto comonadTracedTracedT() -> const boxed&;
auto censor() -> const boxed&;

} // end namespace Control_Comonad_Traced_Class

#endif // Control_Comonad_Traced_Class_H

