// Generated by pscpp compiler

#ifndef Data_Distributive_H
#define Data_Distributive_H

#include "purescript.h"

namespace Data_Distributive {

using namespace purescript;

auto Distributive() -> const boxed&;
auto distributiveIdentity() -> boxed;
auto distribute() -> const boxed&;
auto distributiveFunction() -> boxed;
auto cotraverse() -> const boxed&;
auto collectDefault() -> const boxed&;
auto collect() -> const boxed&;
auto distributeDefault() -> const boxed&;

} // end namespace Data_Distributive

#endif // Data_Distributive_H

