// Generated by pscpp compiler

#ifndef Data_Array_NonEmpty_Internal_H
#define Data_Array_NonEmpty_Internal_H

#include "purescript.h"

namespace Data_Array_NonEmpty_Internal {

using namespace purescript;

auto NonEmptyArray() -> const boxed&;
auto unfoldable1NonEmptyArray() -> boxed;
auto traversableWithIndexNonEmptyArray() -> boxed;
auto traversableNonEmptyArray() -> boxed;
auto showNonEmptyArray() -> const boxed&;
auto semigroupNonEmptyArray() -> boxed;
auto ordNonEmptyArray() -> const boxed&;
auto ord1NonEmptyArray() -> boxed;
auto monadNonEmptyArray() -> boxed;
auto functorWithIndexNonEmptyArray() -> boxed;
auto functorNonEmptyArray() -> boxed;
auto foldableWithIndexNonEmptyArray() -> boxed;
auto foldableNonEmptyArray() -> boxed;
auto foldable1NonEmptyArray() -> boxed;
auto traversable1NonEmptyArray() -> boxed;
auto eqNonEmptyArray() -> const boxed&;
auto eq1NonEmptyArray() -> boxed;
auto bindNonEmptyArray() -> boxed;
auto applyNonEmptyArray() -> boxed;
auto applicativeNonEmptyArray() -> boxed;
auto altNonEmptyArray() -> boxed;
auto fold1Impl() -> const boxed&;
auto traverse1Impl() -> const boxed&;

} // end namespace Data_Array_NonEmpty_Internal

#endif // Data_Array_NonEmpty_Internal_H

