// Generated by pscpp compiler

#ifndef Control_Comonad_Trans_Class_H
#define Control_Comonad_Trans_Class_H

#include "purescript.h"

namespace Control_Comonad_Trans_Class {

using namespace purescript;

auto ComonadTrans() -> const boxed&;
auto lower() -> const boxed&;

} // end namespace Control_Comonad_Trans_Class

#endif // Control_Comonad_Trans_Class_H

