// Generated by pscpp compiler

#ifndef Text_Parsing_Parser_String_H
#define Text_Parsing_Parser_String_H

#include "purescript.h"

namespace Text_Parsing_Parser_String {

using namespace purescript;

auto StringLike() -> const boxed&;
auto uncons() -> const boxed&;
auto stringLikeString() -> boxed;
auto null() -> const boxed&;
auto indexOf() -> const boxed&;
auto eof() -> const boxed&;
auto drop() -> const boxed&;
auto _string_() -> const boxed&;
auto anyChar() -> const boxed&;
auto satisfy() -> const boxed&;
auto _char_() -> const boxed&;
auto noneOf() -> const boxed&;
auto oneOf() -> const boxed&;
auto whiteSpace() -> const boxed&;
auto skipSpaces() -> const boxed&;

} // end namespace Text_Parsing_Parser_String

#endif // Text_Parsing_Parser_String_H

