// Generated by pscpp compiler

#ifndef Data_CommutativeRing_H
#define Data_CommutativeRing_H

#include "purescript.h"

namespace Data_CommutativeRing {

using namespace purescript;

auto CommutativeRingRecord() -> const boxed&;
auto CommutativeRing() -> const boxed&;
auto commutativeRingUnit() -> boxed;
auto commutativeRingRecordNil() -> boxed;
auto commutativeRingRecordCons() -> const boxed&;
auto commutativeRingRecord() -> const boxed&;
auto commutativeRingNumber() -> boxed;
auto commutativeRingInt() -> boxed;
auto commutativeRingFn() -> const boxed&;

} // end namespace Data_CommutativeRing

#endif // Data_CommutativeRing_H

