// Generated by pscpp compiler

#ifndef Control_Monad_Gen_Class_H
#define Control_Monad_Gen_Class_H

#include "purescript.h"

namespace Control_Monad_Gen_Class {

using namespace purescript;

auto MonadGen() -> const boxed&;
auto sized() -> const boxed&;
auto resize() -> const boxed&;
auto chooseInt() -> const boxed&;
auto chooseFloat() -> const boxed&;
auto chooseBool() -> const boxed&;

} // end namespace Control_Monad_Gen_Class

#endif // Control_Monad_Gen_Class_H

