// Generated by pscpp compiler

#ifndef Data_Functor_H
#define Data_Functor_H

#include "purescript.h"

namespace Data_Functor {

using namespace purescript;

auto Functor() -> const boxed&;
auto map() -> const boxed&;
auto mapFlipped() -> const boxed&;
auto _void_() -> const boxed&;
auto voidLeft() -> const boxed&;
auto voidRight() -> const boxed&;
auto functorFn() -> boxed;
auto functorArray() -> boxed;
auto flap() -> const boxed&;
auto arrayMap() -> const boxed&;

} // end namespace Data_Functor

#endif // Data_Functor_H

