// Generated by pscpp compiler

#ifndef Data_List_H
#define Data_List_H

#include "purescript.h"

namespace Data_List {

using namespace purescript;

auto Pattern() -> const boxed&;
auto updateAt() -> const boxed&;
auto unzip() -> boxed;
auto uncons() -> const boxed&;
auto toUnfoldable() -> const boxed&;
auto tail() -> const boxed&;
auto stripPrefix() -> const boxed&;
auto span() -> const boxed&;
auto snoc() -> const boxed&;
auto singleton() -> const boxed&;
auto sortBy() -> const boxed&;
auto sort() -> const boxed&;
auto tails() -> const boxed&;
auto showPattern() -> const boxed&;
auto reverse() -> boxed;
auto take() -> boxed;
auto takeWhile() -> const boxed&;
auto unsnoc() -> const boxed&;
auto zipWith() -> const boxed&;
auto zip() -> boxed;
auto zipWithA() -> const boxed&;
auto range() -> const boxed&;
auto partition() -> const boxed&;
auto null() -> const boxed&;
auto newtypePattern() -> boxed;
auto mapWithIndex() -> boxed;
auto mapMaybe() -> const boxed&;
auto manyRec() -> const boxed&;
auto someRec() -> const boxed&;
auto some() -> const boxed&;
auto many() -> const boxed&;
auto length() -> boxed;
auto last() -> const boxed&;
auto insertBy() -> const boxed&;
auto insertAt() -> const boxed&;
auto insert() -> const boxed&;
auto init() -> const boxed&;
auto index() -> const boxed&;
auto head() -> const boxed&;
auto transpose() -> const boxed&;
auto groupBy() -> const boxed&;
auto group() -> const boxed&;
auto group_Prime_() -> const boxed&;
auto fromFoldable() -> const boxed&;
auto foldM() -> const boxed&;
auto findIndex() -> const boxed&;
auto findLastIndex() -> const boxed&;
auto filterM() -> const boxed&;
auto filter() -> const boxed&;
auto intersectBy() -> const boxed&;
auto intersect() -> const boxed&;
auto nubBy() -> const boxed&;
auto nub() -> const boxed&;
auto eqPattern() -> const boxed&;
auto ordPattern() -> const boxed&;
auto elemLastIndex() -> const boxed&;
auto elemIndex() -> const boxed&;
auto dropWhile() -> const boxed&;
auto dropEnd() -> const boxed&;
auto drop() -> const boxed&;
auto slice() -> const boxed&;
auto takeEnd() -> const boxed&;
auto deleteBy() -> const boxed&;
auto unionBy() -> const boxed&;
auto _union_() -> const boxed&;
auto deleteAt() -> const boxed&;
auto _delete_() -> const boxed&;
auto difference() -> const boxed&;
auto concatMap() -> boxed;
auto concat() -> const boxed&;
auto catMaybes() -> boxed;
auto alterAt() -> const boxed&;
auto modifyAt() -> const boxed&;

} // end namespace Data_List

#endif // Data_List_H

