// Generated by pscpp compiler

#ifndef Control_Comonad_Store_Class_H
#define Control_Comonad_Store_Class_H

#include "purescript.h"

namespace Control_Comonad_Store_Class {

using namespace purescript;

auto ComonadStore() -> const boxed&;
auto pos() -> const boxed&;
auto _peek_() -> const boxed&;
auto peeks() -> const boxed&;
auto seeks() -> const boxed&;
auto seek() -> const boxed&;
auto experiment() -> const boxed&;
auto comonadStoreTracedT() -> const boxed&;
auto comonadStoreStoreT() -> const boxed&;
auto comonadStoreEnvT() -> const boxed&;

} // end namespace Control_Comonad_Store_Class

#endif // Control_Comonad_Store_Class_H

