// Generated by pscpp compiler

#ifndef Control_Comonad_Traced_H
#define Control_Comonad_Traced_H

#include "purescript.h"

namespace Control_Comonad_Traced {

using namespace purescript;

auto traced() -> boxed;
auto runTraced() -> const boxed&;

} // end namespace Control_Comonad_Traced

#endif // Control_Comonad_Traced_H

