// Generated by pscpp compiler

#ifndef Record_Unsafe_H
#define Record_Unsafe_H

#include "purescript.h"

namespace Record_Unsafe {

using namespace purescript;

auto unsafeHas() -> const boxed&;
auto unsafeGet() -> const boxed&;
auto unsafeSet() -> const boxed&;
auto unsafeDelete() -> const boxed&;

} // end namespace Record_Unsafe

#endif // Record_Unsafe_H

