// Generated by pscpp compiler

#ifndef Control_Biapply_H
#define Control_Biapply_H

#include "purescript.h"

namespace Control_Biapply {

using namespace purescript;

auto Biapply() -> const boxed&;
auto biapply() -> const boxed&;
auto biapplyFirst() -> const boxed&;
auto biapplySecond() -> const boxed&;
auto bilift2() -> const boxed&;
auto bilift3() -> const boxed&;

} // end namespace Control_Biapply

#endif // Control_Biapply_H

