// Generated by pscpp compiler

#ifndef Data_String_CodePoints_H
#define Data_String_CodePoints_H

#include "purescript.h"

namespace Data_String_CodePoints {

using namespace purescript;

auto CodePoint() -> const boxed&;
auto unsurrogate() -> const boxed&;
auto showCodePoint() -> boxed;
auto isTrail() -> const boxed&;
auto isLead() -> const boxed&;
auto uncons() -> const boxed&;
auto unconsButWithTuple() -> const boxed&;
auto toCodePointArrayFallback() -> const boxed&;
auto unsafeCodePointAt0Fallback() -> const boxed&;
auto unsafeCodePointAt0() -> boxed;
auto toCodePointArray() -> boxed;
auto length() -> boxed;
auto lastIndexOf() -> const boxed&;
auto indexOf() -> const boxed&;
auto fromCharCode() -> boxed;
auto singletonFallback() -> const boxed&;
auto fromCodePointArray() -> boxed;
auto singleton() -> boxed;
auto takeFallback() -> const boxed&;
auto take() -> boxed;
auto lastIndexOf_Prime_() -> const boxed&;
auto splitAt() -> const boxed&;
auto eqCodePoint() -> boxed;
auto ordCodePoint() -> boxed;
auto drop() -> const boxed&;
auto indexOf_Prime_() -> const boxed&;
auto countTail() -> const boxed&;
auto countFallback() -> const boxed&;
auto countPrefix() -> boxed;
auto dropWhile() -> const boxed&;
auto takeWhile() -> const boxed&;
auto codePointFromChar() -> boxed;
auto codePointAtFallback() -> const boxed&;
auto codePointAt() -> const boxed&;
auto boundedCodePoint() -> boxed;
auto boundedEnumCodePoint() -> boxed;
auto enumCodePoint() -> boxed;
auto _singleton() -> const boxed&;
auto _fromCodePointArray() -> const boxed&;
auto _toCodePointArray() -> const boxed&;
auto _codePointAt() -> const boxed&;
auto _countPrefix() -> const boxed&;
auto _take() -> const boxed&;
auto _unsafeCodePointAt0() -> const boxed&;

} // end namespace Data_String_CodePoints

#endif // Data_String_CodePoints_H

