// Generated by pscpp compiler

#ifndef Data_Ord_Down_H
#define Data_Ord_Down_H

#include "purescript.h"

namespace Data_Ord_Down {

using namespace purescript;

auto Down() -> const boxed&;
auto showDown() -> const boxed&;
auto newtypeDown() -> boxed;
auto eqDown() -> const boxed&;
auto ordDown() -> const boxed&;
auto boundedDown() -> const boxed&;

} // end namespace Data_Ord_Down

#endif // Data_Ord_Down_H

