// Generated by pscpp compiler

#ifndef Data_Char_H
#define Data_Char_H

#include "purescript.h"

namespace Data_Char {

using namespace purescript;

auto toCharCode() -> boxed;
auto fromCharCode() -> boxed;

} // end namespace Data_Char

#endif // Data_Char_H

