// Generated by pscpp compiler

#ifndef Data_Maybe_Last_H
#define Data_Maybe_Last_H

#include "purescript.h"

namespace Data_Maybe_Last {

using namespace purescript;

auto Last() -> const boxed&;
auto showLast() -> const boxed&;
auto semigroupLast() -> boxed;
auto ordLast() -> const boxed&;
auto ord1Last() -> boxed;
auto newtypeLast() -> boxed;
auto monoidLast() -> boxed;
auto monadLast() -> boxed;
auto invariantLast() -> boxed;
auto functorLast() -> boxed;
auto extendLast() -> boxed;
auto eqLast() -> const boxed&;
auto eq1Last() -> boxed;
auto boundedLast() -> const boxed&;
auto bindLast() -> boxed;
auto applyLast() -> boxed;
auto applicativeLast() -> boxed;
auto altLast() -> boxed;
auto plusLast() -> boxed;
auto alternativeLast() -> boxed;
auto monadZeroLast() -> boxed;

} // end namespace Data_Maybe_Last

#endif // Data_Maybe_Last_H

