// Generated by pscpp compiler

#ifndef Type_Data_Row_H
#define Type_Data_Row_H

#include "purescript.h"

namespace Type_Data_Row {

using namespace purescript;

auto RProxy() -> const boxed&;

} // end namespace Type_Data_Row

#endif // Type_Data_Row_H

