// Generated by pscpp compiler

#ifndef Data_FunctorWithIndex_H
#define Data_FunctorWithIndex_H

#include "purescript.h"

namespace Data_FunctorWithIndex {

using namespace purescript;

auto FunctorWithIndex() -> const boxed&;
auto mapWithIndex() -> const boxed&;
auto mapDefault() -> const boxed&;
auto functorWithIndexMultiplicative() -> boxed;
auto functorWithIndexMaybe() -> boxed;
auto functorWithIndexLast() -> boxed;
auto functorWithIndexFirst() -> boxed;
auto functorWithIndexDual() -> boxed;
auto functorWithIndexDisj() -> boxed;
auto functorWithIndexConj() -> boxed;
auto functorWithIndexArray() -> boxed;
auto functorWithIndexAdditive() -> boxed;
auto mapWithIndexArray() -> const boxed&;

} // end namespace Data_FunctorWithIndex

#endif // Data_FunctorWithIndex_H

