// Generated by pscpp compiler

#ifndef Control_Extend_H
#define Control_Extend_H

#include "purescript.h"

namespace Control_Extend {

using namespace purescript;

auto Extend() -> const boxed&;
auto extendFn() -> const boxed&;
auto extendArray() -> boxed;
auto extend() -> const boxed&;
auto extendFlipped() -> const boxed&;
auto duplicate() -> const boxed&;
auto composeCoKleisliFlipped() -> const boxed&;
auto composeCoKleisli() -> const boxed&;
auto arrayExtend() -> const boxed&;

} // end namespace Control_Extend

#endif // Control_Extend_H

