// Generated by pscpp compiler

#ifndef Control_Category_H
#define Control_Category_H

#include "purescript.h"

namespace Control_Category {

using namespace purescript;

auto Category() -> const boxed&;
auto identity() -> const boxed&;
auto categoryFn() -> boxed;

} // end namespace Control_Category

#endif // Control_Category_H

