// Generated by pscpp compiler

#ifndef Data_Newtype_H
#define Data_Newtype_H

#include "purescript.h"

namespace Data_Newtype {

using namespace purescript;

auto Newtype() -> const boxed&;
auto wrap() -> const boxed&;
auto unwrap() -> const boxed&;
auto underF2() -> const boxed&;
auto underF() -> const boxed&;
auto under2() -> const boxed&;
auto under() -> const boxed&;
auto un() -> const boxed&;
auto traverse() -> const boxed&;
auto overF2() -> const boxed&;
auto overF() -> const boxed&;
auto over2() -> const boxed&;
auto over() -> const boxed&;
auto op() -> const boxed&;
auto newtypeMultiplicative() -> boxed;
auto newtypeLast() -> boxed;
auto newtypeFirst() -> boxed;
auto newtypeEndo() -> boxed;
auto newtypeDual() -> boxed;
auto newtypeDisj() -> boxed;
auto newtypeConj() -> boxed;
auto newtypeAdditive() -> boxed;
auto collect() -> const boxed&;
auto alaF() -> const boxed&;
auto ala() -> const boxed&;

} // end namespace Data_Newtype

#endif // Data_Newtype_H

