// Generated by pscpp compiler

#ifndef Data_Int_H
#define Data_Int_H

#include "purescript.h"

namespace Data_Int {

using namespace purescript;

auto Radix() -> const boxed&;
auto Even() -> const boxed&;
auto Odd() -> const boxed&;
auto showParity() -> boxed;
auto radix() -> const boxed&;
auto odd() -> const boxed&;
auto octal() -> const boxed&;
auto hexadecimal() -> const boxed&;
auto fromStringAs() -> boxed;
auto fromString() -> boxed;
auto fromNumber() -> boxed;
auto unsafeClamp() -> const boxed&;
auto round() -> boxed;
auto floor() -> boxed;
auto even() -> const boxed&;
auto parity() -> const boxed&;
auto eqParity() -> boxed;
auto ordParity() -> boxed;
auto semiringParity() -> boxed;
auto ringParity() -> boxed;
auto divisionRingParity() -> boxed;
auto decimal() -> const boxed&;
auto commutativeRingParity() -> boxed;
auto euclideanRingParity() -> boxed;
auto ceil() -> boxed;
auto boundedParity() -> boxed;
auto binary() -> const boxed&;
auto base36() -> const boxed&;
auto fromNumberImpl() -> const boxed&;
auto toNumber() -> const boxed&;
auto quot() -> const boxed&;
auto rem() -> const boxed&;
auto pow() -> const boxed&;
auto fromStringAsImpl() -> const boxed&;
auto toStringAs() -> const boxed&;

} // end namespace Data_Int

#endif // Data_Int_H

