// Generated by pscpp compiler

#ifndef Text_Parsing_Indent_H
#define Text_Parsing_Indent_H

#include "purescript.h"

namespace Text_Parsing_Indent {

using namespace purescript;

auto Opt() -> const boxed&;
auto symbol() -> const boxed&;
auto sourceLine() -> const boxed&;
auto sourceColumn() -> const boxed&;
auto setSourceLine() -> const boxed&;
auto runIndent() -> boxed;
auto put_Prime_() -> const boxed&;
auto many1() -> const boxed&;
auto getPosition() -> const boxed&;
auto get_Prime_() -> boxed;
auto withPos() -> const boxed&;
auto biAp() -> const boxed&;
auto checkIndent() -> boxed;
auto block() -> const boxed&;
auto block1() -> const boxed&;
auto indented() -> boxed;
auto withBlock() -> const boxed&;
auto withBlock_Prime_() -> boxed;
auto indented_Prime_() -> boxed;
auto sameLine() -> boxed;
auto sameOrIndented() -> boxed;
auto indentAp() -> const boxed&;
auto indentMany() -> const boxed&;
auto indentNoAp() -> const boxed&;
auto indentAngles() -> const boxed&;
auto indentBraces() -> const boxed&;
auto indentBrackets() -> const boxed&;
auto indentParens() -> const boxed&;
auto indentOp() -> const boxed&;

} // end namespace Text_Parsing_Indent

#endif // Text_Parsing_Indent_H

