// Generated by pscpp compiler

#ifndef Type_Equality_H
#define Type_Equality_H

#include "purescript.h"

namespace Type_Equality {

using namespace purescript;

auto TypeEquals() -> const boxed&;
auto to() -> const boxed&;
auto refl() -> boxed;
auto from() -> const boxed&;

} // end namespace Type_Equality

#endif // Type_Equality_H

