// Generated by pscpp compiler

#ifndef Data_Bifunctor_Flip_H
#define Data_Bifunctor_Flip_H

#include "purescript.h"

namespace Data_Bifunctor_Flip {

using namespace purescript;

auto Flip() -> const boxed&;
auto showFlip() -> const boxed&;
auto ordFlip() -> const boxed&;
auto newtypeFlip() -> boxed;
auto functorFlip() -> const boxed&;
auto eqFlip() -> const boxed&;
auto bifunctorFlip() -> const boxed&;
auto biapplyFlip() -> const boxed&;
auto biapplicativeFlip() -> const boxed&;

} // end namespace Data_Bifunctor_Flip

#endif // Data_Bifunctor_Flip_H

