// Generated by pscpp compiler

#ifndef Unsafe_Coerce_H
#define Unsafe_Coerce_H

#include "purescript.h"

namespace Unsafe_Coerce {

using namespace purescript;

auto unsafeCoerce() -> const boxed&;

} // end namespace Unsafe_Coerce

#endif // Unsafe_Coerce_H

