// Generated by pscpp compiler

#ifndef Data_Identity_H
#define Data_Identity_H

#include "purescript.h"

namespace Data_Identity {

using namespace purescript;

auto Identity() -> const boxed&;
auto showIdentity() -> const boxed&;
auto semiringIdentity() -> const boxed&;
auto semigroupIdenity() -> const boxed&;
auto ringIdentity() -> const boxed&;
auto ordIdentity() -> const boxed&;
auto newtypeIdentity() -> boxed;
auto monoidIdentity() -> const boxed&;
auto lazyIdentity() -> const boxed&;
auto heytingAlgebraIdentity() -> const boxed&;
auto functorIdentity() -> boxed;
auto functorWithIndexIdentity() -> boxed;
auto invariantIdentity() -> boxed;
auto foldableIdentity() -> boxed;
auto foldableWithIndexIdentity() -> boxed;
auto traversableIdentity() -> boxed;
auto traversableWithIndexIdentity() -> boxed;
auto foldable1Identity() -> boxed;
auto traversable1Identity() -> boxed;
auto extendIdentity() -> boxed;
auto euclideanRingIdentity() -> const boxed&;
auto eqIdentity() -> const boxed&;
auto eq1Identity() -> boxed;
auto ord1Identity() -> boxed;
auto comonadIdentity() -> boxed;
auto commutativeRingIdentity() -> const boxed&;
auto boundedIdentity() -> const boxed&;
auto booleanAlgebraIdentity() -> const boxed&;
auto applyIdentity() -> boxed;
auto bindIdentity() -> boxed;
auto applicativeIdentity() -> boxed;
auto monadIdentity() -> boxed;
auto altIdentity() -> boxed;

} // end namespace Data_Identity

#endif // Data_Identity_H

