// Generated by pscpp compiler

#ifndef Text_Parsing_Parser_Expr_H
#define Text_Parsing_Parser_Expr_H

#include "purescript.h"

namespace Text_Parsing_Parser_Expr {

using namespace purescript;

auto AssocNone() -> const boxed&;
auto AssocLeft() -> const boxed&;
auto AssocRight() -> const boxed&;
auto Infix() -> const boxed&;
auto Prefix() -> const boxed&;
auto Postfix() -> const boxed&;
auto termP() -> const boxed&;
auto splitOp() -> const boxed&;
auto rassocP1() -> const boxed&;
auto rassocP() -> const boxed&;
auto nassocP() -> const boxed&;
auto lassocP1() -> const boxed&;
auto lassocP() -> const boxed&;
auto makeParser() -> const boxed&;
auto buildExprParser() -> const boxed&;

} // end namespace Text_Parsing_Parser_Expr

#endif // Text_Parsing_Parser_Expr_H

