// Generated by pscpp compiler

#ifndef Data_Semigroup_Traversable_H
#define Data_Semigroup_Traversable_H

#include "purescript.h"

namespace Data_Semigroup_Traversable {

using namespace purescript;

auto Traversable1() -> const boxed&;
auto traverse1() -> const boxed&;
auto sequence1Default() -> const boxed&;
auto traversableDual() -> boxed;
auto traversableMultiplicative() -> boxed;
auto sequence1() -> const boxed&;
auto traverse1Default() -> const boxed&;

} // end namespace Data_Semigroup_Traversable

#endif // Data_Semigroup_Traversable_H

