// Generated by pscpp compiler

#ifndef Data_Either_Inject_H
#define Data_Either_Inject_H

#include "purescript.h"

namespace Data_Either_Inject {

using namespace purescript;

auto Inject() -> const boxed&;
auto prj() -> const boxed&;
auto injectReflexive() -> boxed;
auto injectLeft() -> boxed;
auto inj() -> const boxed&;
auto injectRight() -> const boxed&;

} // end namespace Data_Either_Inject

#endif // Data_Either_Inject_H

