// Generated by pscpp compiler

#ifndef Effect_Unsafe_H
#define Effect_Unsafe_H

#include "purescript.h"

namespace Effect_Unsafe {

using namespace purescript;

auto unsafePerformEffect() -> const boxed&;

} // end namespace Effect_Unsafe

#endif // Effect_Unsafe_H

