// Generated by pscpp compiler

#ifndef Data_Bifunctor_Product_H
#define Data_Bifunctor_Product_H

#include "purescript.h"

namespace Data_Bifunctor_Product {

using namespace purescript;

auto Product() -> const boxed&;
auto showProduct() -> const boxed&;
auto eqProduct() -> const boxed&;
auto ordProduct() -> const boxed&;
auto bifunctorProduct() -> const boxed&;
auto biapplyProduct() -> const boxed&;
auto biapplicativeProduct() -> const boxed&;

} // end namespace Data_Bifunctor_Product

#endif // Data_Bifunctor_Product_H

