// Generated by pscpp compiler

#ifndef Data_Ord_H
#define Data_Ord_H

#include "purescript.h"

namespace Data_Ord {

using namespace purescript;

auto Ord() -> const boxed&;
auto Ord1() -> const boxed&;
auto OrdRecord() -> const boxed&;
auto ordVoid() -> boxed;
auto ordUnit() -> boxed;
auto ordString() -> boxed;
auto ordRecordNil() -> boxed;
auto ordOrdering() -> boxed;
auto ordNumber() -> boxed;
auto ordInt() -> boxed;
auto ordChar() -> boxed;
auto ordBoolean() -> boxed;
auto compareRecord() -> const boxed&;
auto ordRecord() -> const boxed&;
auto compare1() -> const boxed&;
auto compare() -> const boxed&;
auto comparing() -> const boxed&;
auto greaterThan() -> const boxed&;
auto greaterThanOrEq() -> const boxed&;
auto signum() -> const boxed&;
auto lessThan() -> const boxed&;
auto lessThanOrEq() -> const boxed&;
auto max() -> const boxed&;
auto min() -> const boxed&;
auto ordArray() -> const boxed&;
auto ord1Array() -> boxed;
auto ordRecordCons() -> const boxed&;
auto clamp() -> const boxed&;
auto between() -> const boxed&;
auto abs() -> const boxed&;
auto ordArrayImpl() -> const boxed&;

} // end namespace Data_Ord

#endif // Data_Ord_H

