// Generated by pscpp compiler

#ifndef Text_Parsing_Parser_Token_H
#define Text_Parsing_Parser_Token_H

#include "purescript.h"

namespace Text_Parsing_Parser_Token {

using namespace purescript;

auto LanguageDef() -> const boxed&;
auto upper() -> const boxed&;
auto unGenLanguageDef() -> const boxed&;
auto token() -> const boxed&;
auto when() -> const boxed&;
auto theReservedNames() -> const boxed&;
auto space() -> const boxed&;
auto simpleSpace() -> const boxed&;
auto oneLineComment() -> const boxed&;
auto octDigit() -> const boxed&;
auto match() -> const boxed&;
auto letter() -> const boxed&;
auto isReserved() -> const boxed&;
auto isReservedName() -> const boxed&;
auto inCommentSingle() -> const boxed&;
auto multiLineComment() -> const boxed&;
auto inCommentMulti() -> const boxed&;
auto inComment() -> const boxed&;
auto whiteSpace_Prime_() -> const boxed&;
auto hexDigit() -> const boxed&;
auto digit() -> const boxed&;
auto makeTokenParser() -> const boxed&;
auto alphaNum() -> const boxed&;

} // end namespace Text_Parsing_Parser_Token

#endif // Text_Parsing_Parser_Token_H

