// Generated by pscpp compiler

#ifndef Effect_Exception_H
#define Effect_Exception_H

#include "purescript.h"

namespace Effect_Exception {

using namespace purescript;

auto _try_() -> const boxed&;
auto _throw_() -> boxed;
auto stack() -> boxed;
auto showError() -> boxed;
auto showErrorImpl() -> const boxed&;
auto error() -> const boxed&;
auto message() -> const boxed&;
auto name() -> const boxed&;
auto stackImpl() -> const boxed&;
auto throwException() -> const boxed&;
auto catchException() -> const boxed&;

} // end namespace Effect_Exception

#endif // Effect_Exception_H

