// Generated by pscpp compiler

#ifndef Data_DivisionRing_H
#define Data_DivisionRing_H

#include "purescript.h"

namespace Data_DivisionRing {

using namespace purescript;

auto DivisionRing() -> const boxed&;
auto recip() -> const boxed&;
auto rightDiv() -> const boxed&;
auto leftDiv() -> const boxed&;
auto divisionringNumber() -> boxed;

} // end namespace Data_DivisionRing

#endif // Data_DivisionRing_H

