// Generated by pscpp compiler

#ifndef Control_Comonad_Env_Class_H
#define Control_Comonad_Env_Class_H

#include "purescript.h"

namespace Control_Comonad_Env_Class {

using namespace purescript;

auto ComonadAsk() -> const boxed&;
auto ComonadEnv() -> const boxed&;
auto local() -> const boxed&;
auto comonadAskTuple() -> boxed;
auto comonadEnvTuple() -> boxed;
auto comonadAskEnvT() -> const boxed&;
auto comonadEnvEnvT() -> const boxed&;
auto ask() -> const boxed&;
auto asks() -> const boxed&;

} // end namespace Control_Comonad_Env_Class

#endif // Control_Comonad_Env_Class_H

