// Generated by pscpp compiler

#ifndef Data_String_H
#define Data_String_H

#include "purescript.h"

namespace Data_String {

using namespace purescript;


} // end namespace Data_String

#endif // Data_String_H

