// Generated by pscpp compiler

#ifndef Data_Monoid_Dual_H
#define Data_Monoid_Dual_H

#include "purescript.h"

namespace Data_Monoid_Dual {

using namespace purescript;

auto Dual() -> const boxed&;
auto showDual() -> const boxed&;
auto semigroupDual() -> const boxed&;
auto ordDual() -> const boxed&;
auto monoidDual() -> const boxed&;
auto functorDual() -> boxed;
auto eqDual() -> const boxed&;
auto eq1Dual() -> boxed;
auto ord1Dual() -> boxed;
auto boundedDual() -> const boxed&;
auto applyDual() -> boxed;
auto bindDual() -> boxed;
auto applicativeDual() -> boxed;
auto monadDual() -> boxed;

} // end namespace Data_Monoid_Dual

#endif // Data_Monoid_Dual_H

