// Generated by pscpp compiler

#ifndef Control_Monad_State_Class_H
#define Control_Monad_State_Class_H

#include "purescript.h"

namespace Control_Monad_State_Class {

using namespace purescript;

auto MonadState() -> const boxed&;
auto state() -> const boxed&;
auto put() -> const boxed&;
auto modify_() -> const boxed&;
auto modify() -> const boxed&;
auto gets() -> const boxed&;
auto get() -> const boxed&;

} // end namespace Control_Monad_State_Class

#endif // Control_Monad_State_Class_H

