// Generated by pscpp compiler

#ifndef Data_Ord_Max_H
#define Data_Ord_Max_H

#include "purescript.h"

namespace Data_Ord_Max {

using namespace purescript;

auto Max() -> const boxed&;
auto showMax() -> const boxed&;
auto semigroupMax() -> const boxed&;
auto newtypeMax() -> boxed;
auto monoidMax() -> const boxed&;
auto eqMax() -> const boxed&;
auto ordMax() -> const boxed&;

} // end namespace Data_Ord_Max

#endif // Data_Ord_Max_H

