// Generated by pscpp compiler

#ifndef Data_List_Partial_H
#define Data_List_Partial_H

#include "purescript.h"

namespace Data_List_Partial {

using namespace purescript;

auto tail() -> const boxed&;
auto last() -> const boxed&;
auto init() -> const boxed&;
auto head() -> const boxed&;

} // end namespace Data_List_Partial

#endif // Data_List_Partial_H

