// Generated by pscpp compiler

#ifndef Control_Monad_Error_Class_H
#define Control_Monad_Error_Class_H

#include "purescript.h"

namespace Control_Monad_Error_Class {

using namespace purescript;

auto MonadThrow() -> const boxed&;
auto MonadError() -> const boxed&;
auto throwError() -> const boxed&;
auto monadThrowMaybe() -> boxed;
auto monadThrowEither() -> boxed;
auto monadThrowEffect() -> boxed;
auto monadErrorMaybe() -> boxed;
auto monadErrorEither() -> boxed;
auto monadErrorEffect() -> boxed;
auto catchError() -> const boxed&;
auto catchJust() -> const boxed&;
auto _try_() -> const boxed&;
auto withResource() -> const boxed&;

} // end namespace Control_Monad_Error_Class

#endif // Control_Monad_Error_Class_H

