// Generated by pscpp compiler

#ifndef Control_Monad_Except_H
#define Control_Monad_Except_H

#include "purescript.h"

namespace Control_Monad_Except {

using namespace purescript;

auto withExcept() -> boxed;
auto runExcept() -> boxed;
auto mapExcept() -> const boxed&;

} // end namespace Control_Monad_Except

#endif // Control_Monad_Except_H

