// Generated by pscpp compiler

#ifndef Data_Either_Nested_H
#define Data_Either_Nested_H

#include "purescript.h"

namespace Data_Either_Nested {

using namespace purescript;

auto in9() -> const boxed&;
auto in8() -> const boxed&;
auto in7() -> const boxed&;
auto in6() -> const boxed&;
auto in5() -> const boxed&;
auto in4() -> const boxed&;
auto in3() -> const boxed&;
auto in2() -> const boxed&;
auto in10() -> const boxed&;
auto in1() -> boxed;
auto either9() -> const boxed&;
auto either8() -> const boxed&;
auto either7() -> const boxed&;
auto either6() -> const boxed&;
auto either5() -> const boxed&;
auto either4() -> const boxed&;
auto either3() -> const boxed&;
auto either2() -> const boxed&;
auto either10() -> const boxed&;
auto either1() -> const boxed&;
auto at9() -> const boxed&;
auto at8() -> const boxed&;
auto at7() -> const boxed&;
auto at6() -> const boxed&;
auto at5() -> const boxed&;
auto at4() -> const boxed&;
auto at3() -> const boxed&;
auto at2() -> const boxed&;
auto at10() -> const boxed&;
auto at1() -> const boxed&;

} // end namespace Data_Either_Nested

#endif // Data_Either_Nested_H

