// Generated by pscpp compiler

#ifndef Data_Monoid_Endo_H
#define Data_Monoid_Endo_H

#include "purescript.h"

namespace Data_Monoid_Endo {

using namespace purescript;

auto Endo() -> const boxed&;
auto showEndo() -> const boxed&;
auto semigroupEndo() -> const boxed&;
auto ordEndo() -> const boxed&;
auto monoidEndo() -> const boxed&;
auto eqEndo() -> const boxed&;
auto boundedEndo() -> const boxed&;

} // end namespace Data_Monoid_Endo

#endif // Data_Monoid_Endo_H

