// Generated by pscpp compiler

#ifndef Global_H
#define Global_H

#include "purescript.h"

namespace Global {

using namespace purescript;

auto nan() -> const boxed&;
auto isNaN() -> const boxed&;
auto infinity() -> const boxed&;
auto isFinite() -> const boxed&;
auto readInt() -> const boxed&;
auto readFloat() -> const boxed&;

} // end namespace Global

#endif // Global_H

