// Generated by pscpp compiler

#ifndef Data_NonEmpty_H
#define Data_NonEmpty_H

#include "purescript.h"

namespace Data_NonEmpty {

using namespace purescript;

auto NonEmpty() -> const boxed&;
auto unfoldable1NonEmpty() -> const boxed&;
auto tail() -> const boxed&;
auto singleton() -> const boxed&;
auto showNonEmpty() -> const boxed&;
auto oneOf() -> const boxed&;
auto head() -> const boxed&;
auto functorNonEmpty() -> const boxed&;
auto functorWithIndex() -> const boxed&;
auto fromNonEmpty() -> const boxed&;
auto foldl1() -> const boxed&;
auto foldableNonEmpty() -> const boxed&;
auto foldableWithIndexNonEmpty() -> const boxed&;
auto traversableNonEmpty() -> const boxed&;
auto traversableWithIndexNonEmpty() -> const boxed&;
auto foldable1NonEmpty() -> const boxed&;
auto eqNonEmpty() -> const boxed&;
auto ordNonEmpty() -> const boxed&;
auto eq1NonEmpty() -> const boxed&;
auto ord1NonEmpty() -> const boxed&;

} // end namespace Data_NonEmpty

#endif // Data_NonEmpty_H

