// Generated by pscpp compiler

#ifndef Data_String_Gen_H
#define Data_String_Gen_H

#include "purescript.h"

namespace Data_String_Gen {

using namespace purescript;

auto genString() -> const boxed&;
auto genUnicodeString() -> const boxed&;
auto genDigitString() -> const boxed&;
auto genAsciiString_Prime_() -> const boxed&;
auto genAsciiString() -> const boxed&;
auto genAlphaUppercaseString() -> const boxed&;
auto genAlphaString() -> const boxed&;
auto genAlphaLowercaseString() -> const boxed&;

} // end namespace Data_String_Gen

#endif // Data_String_Gen_H

