// Generated by pscpp compiler

#ifndef Data_Functor_Invariant_H
#define Data_Functor_Invariant_H

#include "purescript.h"

namespace Data_Functor_Invariant {

using namespace purescript;

auto Invariant() -> const boxed&;
auto invariantMultiplicative() -> boxed;
auto invariantEndo() -> boxed;
auto invariantDual() -> boxed;
auto invariantDisj() -> boxed;
auto invariantConj() -> boxed;
auto invariantAdditive() -> boxed;
auto imapF() -> const boxed&;
auto invariantArray() -> boxed;
auto invariantFn() -> boxed;
auto imap() -> const boxed&;

} // end namespace Data_Functor_Invariant

#endif // Data_Functor_Invariant_H

