// Generated by pscpp compiler

#ifndef Data_Bifoldable_H
#define Data_Bifoldable_H

#include "purescript.h"

namespace Data_Bifoldable {

using namespace purescript;

auto Bifoldable() -> const boxed&;
auto bifoldr() -> const boxed&;
auto bitraverse_() -> const boxed&;
auto bifor_() -> const boxed&;
auto bisequence_() -> const boxed&;
auto bifoldl() -> const boxed&;
auto bifoldableJoker() -> const boxed&;
auto bifoldableClown() -> const boxed&;
auto bifoldMapDefaultR() -> const boxed&;
auto bifoldMapDefaultL() -> const boxed&;
auto bifoldMap() -> const boxed&;
auto bifoldableFlip() -> const boxed&;
auto bifoldableWrap() -> const boxed&;
auto bifoldlDefault() -> const boxed&;
auto bifoldrDefault() -> const boxed&;
auto bifoldableProduct() -> const boxed&;
auto bifold() -> const boxed&;
auto biany() -> const boxed&;
auto biall() -> const boxed&;

} // end namespace Data_Bifoldable

#endif // Data_Bifoldable_H

