// Generated by pscpp compiler

#ifndef Control_Monad_ST_Ref_H
#define Control_Monad_ST_Ref_H

#include "purescript.h"

namespace Control_Monad_ST_Ref {

using namespace purescript;


} // end namespace Control_Monad_ST_Ref

#endif // Control_Monad_ST_Ref_H

