// Generated by pscpp compiler

#ifndef Effect_Class_H
#define Effect_Class_H

#include "purescript.h"

namespace Effect_Class {

using namespace purescript;

auto MonadEffect() -> const boxed&;
auto monadEffectEffect() -> boxed;
auto liftEffect() -> const boxed&;

} // end namespace Effect_Class

#endif // Effect_Class_H

