// Generated by pscpp compiler

#ifndef Data_Unfoldable1_H
#define Data_Unfoldable1_H

#include "purescript.h"

namespace Data_Unfoldable1 {

using namespace purescript;

auto Unfoldable1() -> const boxed&;
auto unfoldr1() -> const boxed&;
auto unfoldable1Array() -> boxed;
auto replicate1() -> const boxed&;
auto replicate1A() -> const boxed&;
auto singleton() -> const boxed&;
auto range() -> const boxed&;
auto unfoldr1ArrayImpl() -> const boxed&;

} // end namespace Data_Unfoldable1

#endif // Data_Unfoldable1_H

