// Generated by pscpp compiler

#ifndef Control_Monad_Trans_Class_H
#define Control_Monad_Trans_Class_H

#include "purescript.h"

namespace Control_Monad_Trans_Class {

using namespace purescript;

auto MonadTrans() -> const boxed&;
auto lift() -> const boxed&;

} // end namespace Control_Monad_Trans_Class

#endif // Control_Monad_Trans_Class_H

