// Generated by pscpp compiler

#ifndef Control_Monad_Writer_H
#define Control_Monad_Writer_H

#include "purescript.h"

namespace Control_Monad_Writer {

using namespace purescript;

auto writer() -> boxed;
auto runWriter() -> boxed;
auto mapWriter() -> const boxed&;
auto execWriter() -> const boxed&;

} // end namespace Control_Monad_Writer

#endif // Control_Monad_Writer_H

