// Generated by pscpp compiler

#ifndef Control_Monad_Cont_Class_H
#define Control_Monad_Cont_Class_H

#include "purescript.h"

namespace Control_Monad_Cont_Class {

using namespace purescript;

auto MonadCont() -> const boxed&;
auto callCC() -> const boxed&;

} // end namespace Control_Monad_Cont_Class

#endif // Control_Monad_Cont_Class_H

