// Generated by pscpp compiler

#ifndef Data_String_Unsafe_H
#define Data_String_Unsafe_H

#include "purescript.h"

namespace Data_String_Unsafe {

using namespace purescript;

auto charAt() -> const boxed&;
auto _char_() -> const boxed&;

} // end namespace Data_String_Unsafe

#endif // Data_String_Unsafe_H

