// Generated by pscpp compiler

#ifndef Data_Symbol_H
#define Data_Symbol_H

#include "purescript.h"

namespace Data_Symbol {

using namespace purescript;

auto SProxy() -> const boxed&;
auto IsSymbol() -> const boxed&;
auto reifySymbol() -> const boxed&;
auto reflectSymbol() -> const boxed&;
auto unsafeCoerce() -> const boxed&;

} // end namespace Data_Symbol

#endif // Data_Symbol_H

