// Generated by pscpp compiler

#ifndef Math_H
#define Math_H

#include "purescript.h"

namespace Math {

using namespace purescript;

auto abs() -> const boxed&;
auto acos() -> const boxed&;
auto asin() -> const boxed&;
auto atan() -> const boxed&;
auto atan2() -> const boxed&;
auto ceil() -> const boxed&;
auto cos() -> const boxed&;
auto exp() -> const boxed&;
auto floor() -> const boxed&;
auto log() -> const boxed&;
auto max() -> const boxed&;
auto min() -> const boxed&;
auto pow() -> const boxed&;
auto round() -> const boxed&;
auto sin() -> const boxed&;
auto sqrt() -> const boxed&;
auto tan() -> const boxed&;
auto trunc() -> const boxed&;
auto remainder() -> const boxed&;
auto e() -> const boxed&;
auto ln2() -> const boxed&;
auto ln10() -> const boxed&;
auto log2e() -> const boxed&;
auto log10e() -> const boxed&;
auto pi() -> const boxed&;
auto tau() -> const boxed&;
auto sqrt1_2() -> const boxed&;
auto sqrt2() -> const boxed&;

} // end namespace Math

#endif // Math_H

