// Generated by pscpp compiler

#ifndef Control_MonadZero_H
#define Control_MonadZero_H

#include "purescript.h"

namespace Control_MonadZero {

using namespace purescript;

auto MonadZero() -> const boxed&;
auto monadZeroArray() -> boxed;
auto guard() -> const boxed&;

} // end namespace Control_MonadZero

#endif // Control_MonadZero_H

