// Generated by pscpp compiler

#ifndef Control_Monad_Cont_H
#define Control_Monad_Cont_H

#include "purescript.h"

namespace Control_Monad_Cont {

using namespace purescript;

auto withCont() -> const boxed&;
auto runCont() -> const boxed&;
auto mapCont() -> const boxed&;
auto cont() -> const boxed&;

} // end namespace Control_Monad_Cont

#endif // Control_Monad_Cont_H

