// Generated by pscpp compiler

#ifndef Data_Ord_Unsafe_H
#define Data_Ord_Unsafe_H

#include "purescript.h"

namespace Data_Ord_Unsafe {

using namespace purescript;

auto unsafeCompare() -> boxed;
auto unsafeCompareImpl() -> const boxed&;

} // end namespace Data_Ord_Unsafe

#endif // Data_Ord_Unsafe_H

