// Generated by pscpp compiler

#ifndef Control_Monad_H
#define Control_Monad_H

#include "purescript.h"

namespace Control_Monad {

using namespace purescript;

auto Monad() -> const boxed&;
auto whenM() -> const boxed&;
auto unlessM() -> const boxed&;
auto monadFn() -> boxed;
auto monadArray() -> boxed;
auto liftM1() -> const boxed&;
auto ap() -> const boxed&;

} // end namespace Control_Monad

#endif // Control_Monad_H

