// Generated by pscpp compiler

#ifndef Data_Enum_Gen_H
#define Data_Enum_Gen_H

#include "purescript.h"

namespace Data_Enum_Gen {

using namespace purescript;

auto genBoundedEnum() -> const boxed&;

} // end namespace Data_Enum_Gen

#endif // Data_Enum_Gen_H

