// Generated by pscpp compiler

#ifndef Effect_Ref_H
#define Effect_Ref_H

#include "purescript.h"

namespace Effect_Ref {

using namespace purescript;

auto modify() -> const boxed&;
auto modify_() -> const boxed&;
auto _new_() -> const boxed&;
auto read() -> const boxed&;
auto modify_Prime_() -> const boxed&;
auto write() -> const boxed&;

} // end namespace Effect_Ref

#endif // Effect_Ref_H

