// Generated by pscpp compiler

#ifndef Data_BooleanAlgebra_H
#define Data_BooleanAlgebra_H

#include "purescript.h"

namespace Data_BooleanAlgebra {

using namespace purescript;

auto BooleanAlgebra() -> const boxed&;
auto BooleanAlgebraRecord() -> const boxed&;
auto booleanAlgebraUnit() -> boxed;
auto booleanAlgebraRecordNil() -> boxed;
auto booleanAlgebraRecordCons() -> const boxed&;
auto booleanAlgebraRecord() -> const boxed&;
auto booleanAlgebraFn() -> const boxed&;
auto booleanAlgebraBoolean() -> boxed;

} // end namespace Data_BooleanAlgebra

#endif // Data_BooleanAlgebra_H

