// Generated by pscpp compiler

#ifndef Effect_H
#define Effect_H

#include "purescript.h"

namespace Effect {

using namespace purescript;

auto monadEffect() -> boxed;
auto bindEffect() -> boxed;
auto applyEffect() -> boxed;
auto applicativeEffect() -> boxed;
auto functorEffect() -> boxed;
auto semigroupEffect() -> const boxed&;
auto monoidEffect() -> const boxed&;
auto pureE() -> const boxed&;
auto bindE() -> const boxed&;
auto untilE() -> const boxed&;
auto whileE() -> const boxed&;
auto forE() -> const boxed&;
auto foreachE() -> const boxed&;

} // end namespace Effect

#endif // Effect_H

