// Generated by pscpp compiler

#ifndef Data_Semigroup_First_H
#define Data_Semigroup_First_H

#include "purescript.h"

namespace Data_Semigroup_First {

using namespace purescript;

auto First() -> const boxed&;
auto showFirst() -> const boxed&;
auto semigroupFirst() -> boxed;
auto ordFirst() -> const boxed&;
auto functorFirst() -> boxed;
auto eqFirst() -> const boxed&;
auto eq1First() -> boxed;
auto ord1First() -> boxed;
auto boundedFirst() -> const boxed&;
auto applyFirst() -> boxed;
auto bindFirst() -> boxed;
auto applicativeFirst() -> boxed;
auto monadFirst() -> boxed;

} // end namespace Data_Semigroup_First

#endif // Data_Semigroup_First_H

