// Generated by pscpp compiler

#ifndef Control_Monad_Rec_Class_H
#define Control_Monad_Rec_Class_H

#include "purescript.h"

namespace Control_Monad_Rec_Class {

using namespace purescript;

auto Loop() -> const boxed&;
auto Done() -> const boxed&;
auto MonadRec() -> const boxed&;
auto tailRecM() -> const boxed&;
auto tailRecM2() -> const boxed&;
auto tailRecM3() -> const boxed&;
auto tailRec() -> const boxed&;
auto monadRecMaybe() -> boxed;
auto monadRecIdentity() -> boxed;
auto monadRecFunction() -> boxed;
auto monadRecEither() -> boxed;
auto monadRecEffect() -> boxed;
auto functorStep() -> boxed;
auto forever() -> const boxed&;
auto bifunctorStep() -> boxed;

} // end namespace Control_Monad_Rec_Class

#endif // Control_Monad_Rec_Class_H

