// Generated by pscpp compiler

#ifndef Data_Bounded_H
#define Data_Bounded_H

#include "purescript.h"

namespace Data_Bounded {

using namespace purescript;

auto Bounded() -> const boxed&;
auto top() -> const boxed&;
auto boundedUnit() -> boxed;
auto boundedOrdering() -> boxed;
auto boundedNumber() -> boxed;
auto boundedInt() -> boxed;
auto boundedChar() -> boxed;
auto boundedBoolean() -> boxed;
auto bottom() -> const boxed&;
auto topInt() -> const boxed&;
auto bottomInt() -> const boxed&;
auto topChar() -> const boxed&;
auto bottomChar() -> const boxed&;
auto topNumber() -> const boxed&;
auto bottomNumber() -> const boxed&;

} // end namespace Data_Bounded

#endif // Data_Bounded_H

