// Generated by pscpp compiler

#ifndef Data_String_NonEmpty_H
#define Data_String_NonEmpty_H

#include "purescript.h"

namespace Data_String_NonEmpty {

using namespace purescript;


} // end namespace Data_String_NonEmpty

#endif // Data_String_NonEmpty_H

