// Generated by pscpp compiler

#ifndef Data_Int_Bits_H
#define Data_Int_Bits_H

#include "purescript.h"

namespace Data_Int_Bits {

using namespace purescript;

auto _and_() -> const boxed&;
auto _or_() -> const boxed&;
auto _xor_() -> const boxed&;
auto shl() -> const boxed&;
auto shr() -> const boxed&;
auto zshr() -> const boxed&;
auto complement() -> const boxed&;

} // end namespace Data_Int_Bits

#endif // Data_Int_Bits_H

