// Generated by pscpp compiler

#ifndef Control_Biapplicative_H
#define Control_Biapplicative_H

#include "purescript.h"

namespace Control_Biapplicative {

using namespace purescript;

auto Biapplicative() -> const boxed&;
auto bipure() -> const boxed&;

} // end namespace Control_Biapplicative

#endif // Control_Biapplicative_H

