// Generated by pscpp compiler

#ifndef Control_Comonad_H
#define Control_Comonad_H

#include "purescript.h"

namespace Control_Comonad {

using namespace purescript;

auto Comonad() -> const boxed&;
auto extract() -> const boxed&;

} // end namespace Control_Comonad

#endif // Control_Comonad_H

