// Generated by pscpp compiler

#ifndef Data_Bifunctor_Wrap_H
#define Data_Bifunctor_Wrap_H

#include "purescript.h"

namespace Data_Bifunctor_Wrap {

using namespace purescript;

auto Wrap() -> const boxed&;
auto showWrap() -> const boxed&;
auto ordWrap() -> const boxed&;
auto newtypeWrap() -> boxed;
auto functorWrap() -> const boxed&;
auto eqWrap() -> const boxed&;
auto bifunctorWrap() -> const boxed&;
auto biapplyWrap() -> const boxed&;
auto biapplicativeWrap() -> const boxed&;

} // end namespace Data_Bifunctor_Wrap

#endif // Data_Bifunctor_Wrap_H

