// Generated by pscpp compiler

#ifndef Control_Lazy_H
#define Control_Lazy_H

#include "purescript.h"

namespace Control_Lazy {

using namespace purescript;

auto Lazy() -> const boxed&;
auto lazyUnit() -> boxed;
auto lazyFn() -> boxed;
auto defer() -> const boxed&;
auto fix() -> const boxed&;

} // end namespace Control_Lazy

#endif // Control_Lazy_H

