// Generated by pscpp compiler

#ifndef Control_Comonad_Traced_Trans_H
#define Control_Comonad_Traced_Trans_H

#include "purescript.h"

namespace Control_Comonad_Traced_Trans {

using namespace purescript;

auto TracedT() -> const boxed&;
auto runTracedT() -> const boxed&;
auto newtypeTracedT() -> boxed;
auto functorTracedT() -> const boxed&;
auto extendTracedT() -> const boxed&;
auto comonadTransTracedT() -> const boxed&;
auto comonadTracedT() -> const boxed&;

} // end namespace Control_Comonad_Traced_Trans

#endif // Control_Comonad_Traced_Trans_H

