// Generated by pscpp compiler

#ifndef Data_Semigroup_Foldable_H
#define Data_Semigroup_Foldable_H

#include "purescript.h"

namespace Data_Semigroup_Foldable {

using namespace purescript;

auto JoinWith() -> const boxed&;
auto Act() -> const boxed&;
auto Foldable1() -> const boxed&;
auto semigroupJoinWith() -> const boxed&;
auto semigroupAct() -> const boxed&;
auto joinee() -> const boxed&;
auto getAct() -> const boxed&;
auto foldMap1() -> const boxed&;
auto intercalateMap() -> const boxed&;
auto intercalate() -> const boxed&;
auto maximum() -> const boxed&;
auto minimum() -> const boxed&;
auto traverse1_() -> const boxed&;
auto for1_() -> const boxed&;
auto sequence1_() -> const boxed&;
auto fold1Default() -> const boxed&;
auto foldableDual() -> boxed;
auto foldableMultiplicative() -> boxed;
auto fold1() -> const boxed&;
auto foldMap1Default() -> const boxed&;

} // end namespace Data_Semigroup_Foldable

#endif // Data_Semigroup_Foldable_H

