// Generated by pscpp compiler

#ifndef Control_Monad_Gen_Common_H
#define Control_Monad_Gen_Common_H

#include "purescript.h"

namespace Control_Monad_Gen_Common {

using namespace purescript;

auto genTuple() -> const boxed&;
auto genNonEmpty() -> const boxed&;
auto genMaybe_Prime_() -> const boxed&;
auto genMaybe() -> const boxed&;
auto genIdentity() -> const boxed&;
auto genEither_Prime_() -> const boxed&;
auto genEither() -> const boxed&;

} // end namespace Control_Monad_Gen_Common

#endif // Control_Monad_Gen_Common_H

