// Generated by pscpp compiler

#ifndef Control_Monad_State_H
#define Control_Monad_State_H

#include "purescript.h"

namespace Control_Monad_State {

using namespace purescript;

auto withState() -> boxed;
auto runState() -> const boxed&;
auto mapState() -> const boxed&;
auto execState() -> const boxed&;
auto evalState() -> const boxed&;

} // end namespace Control_Monad_State

#endif // Control_Monad_State_H

