// Generated by pscpp compiler

#ifndef Data_String_CodeUnits_H
#define Data_String_CodeUnits_H

#include "purescript.h"

namespace Data_String_CodeUnits {

using namespace purescript;

auto uncons() -> const boxed&;
auto toChar() -> boxed;
auto takeWhile() -> const boxed&;
auto takeRight() -> const boxed&;
auto slice() -> const boxed&;
auto lastIndexOf_Prime_() -> boxed;
auto lastIndexOf() -> boxed;
auto stripSuffix() -> const boxed&;
auto indexOf_Prime_() -> boxed;
auto indexOf() -> boxed;
auto stripPrefix() -> const boxed&;
auto dropWhile() -> const boxed&;
auto dropRight() -> const boxed&;
auto contains() -> const boxed&;
auto charAt() -> boxed;
auto singleton() -> const boxed&;
auto fromCharArray() -> const boxed&;
auto toCharArray() -> const boxed&;
auto _charAt() -> const boxed&;
auto _toChar() -> const boxed&;
auto length() -> const boxed&;
auto countPrefix() -> const boxed&;
auto _indexOf() -> const boxed&;
auto _indexOf_Prime_() -> const boxed&;
auto _lastIndexOf() -> const boxed&;
auto _lastIndexOf_Prime_() -> const boxed&;
auto take() -> const boxed&;
auto drop() -> const boxed&;
auto _slice() -> const boxed&;
auto splitAt() -> const boxed&;

} // end namespace Data_String_CodeUnits

#endif // Data_String_CodeUnits_H

