// Generated by pscpp compiler

#ifndef Text_Parsing_Parser_Language_H
#define Text_Parsing_Parser_Language_H

#include "purescript.h"

namespace Text_Parsing_Parser_Language {

using namespace purescript;

auto emptyDef() -> boxed;
auto haskellStyle() -> boxed;
auto haskell98Def() -> boxed;
auto haskellDef() -> const boxed&;
auto haskell() -> boxed;
auto javaStyle() -> boxed;

} // end namespace Text_Parsing_Parser_Language

#endif // Text_Parsing_Parser_Language_H

