// Generated by pscpp compiler

#ifndef Control_Monad_Writer_Trans_H
#define Control_Monad_Writer_Trans_H

#include "purescript.h"

namespace Control_Monad_Writer_Trans {

using namespace purescript;

auto WriterT() -> const boxed&;
auto runWriterT() -> const boxed&;
auto newtypeWriterT() -> boxed;
auto monadTransWriterT() -> const boxed&;
auto mapWriterT() -> const boxed&;
auto functorWriterT() -> const boxed&;
auto execWriterT() -> const boxed&;
auto applyWriterT() -> const boxed&;
auto bindWriterT() -> const boxed&;
auto applicativeWriterT() -> const boxed&;
auto monadWriterT() -> const boxed&;
auto monadAskWriterT() -> const boxed&;
auto monadReaderWriterT() -> const boxed&;
auto monadContWriterT() -> const boxed&;
auto monadEffectWriter() -> const boxed&;
auto monadRecWriterT() -> const boxed&;
auto monadStateWriterT() -> const boxed&;
auto monadTellWriterT() -> const boxed&;
auto monadWriterWriterT() -> const boxed&;
auto monadThrowWriterT() -> const boxed&;
auto monadErrorWriterT() -> const boxed&;
auto altWriterT() -> const boxed&;
auto plusWriterT() -> const boxed&;
auto alternativeWriterT() -> const boxed&;
auto monadZeroWriterT() -> const boxed&;
auto monadPlusWriterT() -> const boxed&;

} // end namespace Control_Monad_Writer_Trans

#endif // Control_Monad_Writer_Trans_H

