// Generated by pscpp compiler

#ifndef Data_String_Pattern_H
#define Data_String_Pattern_H

#include "purescript.h"

namespace Data_String_Pattern {

using namespace purescript;

auto Replacement() -> const boxed&;
auto Pattern() -> const boxed&;
auto showReplacement() -> boxed;
auto showPattern() -> boxed;
auto newtypeReplacement() -> boxed;
auto newtypePattern() -> boxed;
auto eqReplacement() -> boxed;
auto ordReplacement() -> boxed;
auto eqPattern() -> boxed;
auto ordPattern() -> boxed;

} // end namespace Data_String_Pattern

#endif // Data_String_Pattern_H

