// Generated by pscpp compiler

#ifndef Data_String_Regex_Flags_H
#define Data_String_Regex_Flags_H

#include "purescript.h"

namespace Data_String_Regex_Flags {

using namespace purescript;

auto RegexFlags() -> const boxed&;
auto unicode() -> boxed;
auto sticky() -> boxed;
auto showRegexFlags() -> boxed;
auto semigroupRegexFlags() -> boxed;
auto noFlags() -> boxed;
auto multiline() -> boxed;
auto monoidRegexFlags() -> boxed;
auto ignoreCase() -> boxed;
auto global() -> boxed;
auto eqRegexFlags() -> boxed;

} // end namespace Data_String_Regex_Flags

#endif // Data_String_Regex_Flags_H

