// Generated by pscpp compiler

#ifndef Control_Monad_Cont_Trans_H
#define Control_Monad_Cont_Trans_H

#include "purescript.h"

namespace Control_Monad_Cont_Trans {

using namespace purescript;

auto ContT() -> const boxed&;
auto withContT() -> const boxed&;
auto runContT() -> const boxed&;
auto newtypeContT() -> boxed;
auto monadTransContT() -> boxed;
auto mapContT() -> const boxed&;
auto functorContT() -> const boxed&;
auto applyContT() -> const boxed&;
auto bindContT() -> const boxed&;
auto applicativeContT() -> const boxed&;
auto monadContT() -> const boxed&;
auto monadAskContT() -> const boxed&;
auto monadReaderContT() -> const boxed&;
auto monadContContT() -> const boxed&;
auto monadEffectContT() -> const boxed&;
auto monadStateContT() -> const boxed&;

} // end namespace Control_Monad_Cont_Trans

#endif // Control_Monad_Cont_Trans_H

