// Generated by pscpp compiler

#ifndef Text_Parsing_Parser_Pos_H
#define Text_Parsing_Parser_Pos_H

#include "purescript.h"

namespace Text_Parsing_Parser_Pos {

using namespace purescript;

auto Position() -> const boxed&;
auto updatePosString() -> const boxed&;
auto showPosition() -> boxed;
auto initialPos() -> const boxed&;
auto eqPosition() -> boxed;
auto ordPosition() -> boxed;

} // end namespace Text_Parsing_Parser_Pos

#endif // Text_Parsing_Parser_Pos_H

