// Generated by pscpp compiler

#ifndef Data_List_ZipList_H
#define Data_List_ZipList_H

#include "purescript.h"

namespace Data_List_ZipList {

using namespace purescript;

auto ZipList() -> const boxed&;
auto traversableZipList() -> boxed;
auto showZipList() -> const boxed&;
auto semigroupZipList() -> boxed;
auto ordZipList() -> const boxed&;
auto newtypeZipList() -> boxed;
auto monoidZipList() -> boxed;
auto functorZipList() -> boxed;
auto foldableZipList() -> boxed;
auto eqZipList() -> const boxed&;
auto applyZipList() -> boxed;
auto zipListIsNotBind() -> const boxed&;
auto applicativeZipList() -> boxed;
auto altZipList() -> boxed;
auto plusZipList() -> boxed;
auto alternativeZipList() -> boxed;

} // end namespace Data_List_ZipList

#endif // Data_List_ZipList_H

