// Generated by pscpp compiler

#ifndef Type_Data_RowList_H
#define Type_Data_RowList_H

#include "purescript.h"

namespace Type_Data_RowList {

using namespace purescript;

auto RLProxy() -> const boxed&;

} // end namespace Type_Data_RowList

#endif // Type_Data_RowList_H

