// Generated by pscpp compiler

#ifndef Data_Monoid_H
#define Data_Monoid_H

#include "purescript.h"

namespace Data_Monoid {

using namespace purescript;

auto MonoidRecord() -> const boxed&;
auto Monoid() -> const boxed&;
auto monoidUnit() -> boxed;
auto monoidString() -> boxed;
auto monoidRecordNil() -> boxed;
auto monoidOrdering() -> boxed;
auto monoidArray() -> boxed;
auto memptyRecord() -> const boxed&;
auto monoidRecord() -> const boxed&;
auto mempty() -> const boxed&;
auto monoidFn() -> const boxed&;
auto monoidRecordCons() -> const boxed&;
auto power() -> const boxed&;
auto guard() -> const boxed&;

} // end namespace Data_Monoid

#endif // Data_Monoid_H

