// Generated by pscpp compiler

#ifndef Data_Field_H
#define Data_Field_H

#include "purescript.h"

namespace Data_Field {

using namespace purescript;

auto Field() -> const boxed&;
auto field() -> const boxed&;

} // end namespace Data_Field

#endif // Data_Field_H

