// Generated by pscpp compiler

#ifndef Effect_Class_Console_H
#define Effect_Class_Console_H

#include "purescript.h"

namespace Effect_Class_Console {

using namespace purescript;

auto warnShow() -> const boxed&;
auto warn() -> const boxed&;
auto timeEnd() -> const boxed&;
auto time() -> const boxed&;
auto logShow() -> const boxed&;
auto log() -> const boxed&;
auto infoShow() -> const boxed&;
auto info() -> const boxed&;
auto errorShow() -> const boxed&;
auto error() -> const boxed&;

} // end namespace Effect_Class_Console

#endif // Effect_Class_Console_H

