// Generated by pscpp compiler

#ifndef Control_Monad_RWS_Trans_H
#define Control_Monad_RWS_Trans_H

#include "purescript.h"

namespace Control_Monad_RWS_Trans {

using namespace purescript;

auto RWSResult() -> const boxed&;
auto RWST() -> const boxed&;
auto withRWST() -> const boxed&;
auto runRWST() -> const boxed&;
auto newtypeRWST() -> boxed;
auto monadTransRWST() -> const boxed&;
auto mapRWST() -> const boxed&;
auto lazyRWST() -> boxed;
auto functorRWST() -> const boxed&;
auto execRWST() -> const boxed&;
auto evalRWST() -> const boxed&;
auto applyRWST() -> const boxed&;
auto bindRWST() -> const boxed&;
auto applicativeRWST() -> const boxed&;
auto monadRWST() -> const boxed&;
auto monadAskRWST() -> const boxed&;
auto monadReaderRWST() -> const boxed&;
auto monadEffectRWS() -> const boxed&;
auto monadRecRWST() -> const boxed&;
auto monadStateRWST() -> const boxed&;
auto monadTellRWST() -> const boxed&;
auto monadWriterRWST() -> const boxed&;
auto monadThrowRWST() -> const boxed&;
auto monadErrorRWST() -> const boxed&;
auto altRWST() -> const boxed&;
auto plusRWST() -> const boxed&;
auto alternativeRWST() -> const boxed&;

} // end namespace Control_Monad_RWS_Trans

#endif // Control_Monad_RWS_Trans_H

