// Generated by pscpp compiler

#ifndef Control_Semigroupoid_H
#define Control_Semigroupoid_H

#include "purescript.h"

namespace Control_Semigroupoid {

using namespace purescript;

auto Semigroupoid() -> const boxed&;
auto semigroupoidFn() -> boxed;
auto compose() -> const boxed&;
auto composeFlipped() -> const boxed&;

} // end namespace Control_Semigroupoid

#endif // Control_Semigroupoid_H

