// Generated by pscpp compiler

#ifndef Data_Tuple_Nested_H
#define Data_Tuple_Nested_H

#include "purescript.h"

namespace Data_Tuple_Nested {

using namespace purescript;

auto uncurry9() -> const boxed&;
auto uncurry8() -> const boxed&;
auto uncurry7() -> const boxed&;
auto uncurry6() -> const boxed&;
auto uncurry5() -> const boxed&;
auto uncurry4() -> const boxed&;
auto uncurry3() -> const boxed&;
auto uncurry2() -> const boxed&;
auto uncurry10() -> const boxed&;
auto uncurry1() -> const boxed&;
auto tuple9() -> const boxed&;
auto tuple8() -> const boxed&;
auto tuple7() -> const boxed&;
auto tuple6() -> const boxed&;
auto tuple5() -> const boxed&;
auto tuple4() -> const boxed&;
auto tuple3() -> const boxed&;
auto tuple2() -> const boxed&;
auto tuple10() -> const boxed&;
auto tuple1() -> const boxed&;
auto over9() -> const boxed&;
auto over8() -> const boxed&;
auto over7() -> const boxed&;
auto over6() -> const boxed&;
auto over5() -> const boxed&;
auto over4() -> const boxed&;
auto over3() -> const boxed&;
auto over2() -> const boxed&;
auto over10() -> const boxed&;
auto over1() -> const boxed&;
auto get9() -> const boxed&;
auto get8() -> const boxed&;
auto get7() -> const boxed&;
auto get6() -> const boxed&;
auto get5() -> const boxed&;
auto get4() -> const boxed&;
auto get3() -> const boxed&;
auto get2() -> const boxed&;
auto get10() -> const boxed&;
auto get1() -> const boxed&;
auto curry9() -> const boxed&;
auto curry8() -> const boxed&;
auto curry7() -> const boxed&;
auto curry6() -> const boxed&;
auto curry5() -> const boxed&;
auto curry4() -> const boxed&;
auto curry3() -> const boxed&;
auto curry2() -> const boxed&;
auto curry10() -> const boxed&;
auto curry1() -> const boxed&;

} // end namespace Data_Tuple_Nested

#endif // Data_Tuple_Nested_H

