// Generated by pscpp compiler

#ifndef Control_Apply_H
#define Control_Apply_H

#include "purescript.h"

namespace Control_Apply {

using namespace purescript;

auto Apply() -> const boxed&;
auto applyFn() -> boxed;
auto applyArray() -> boxed;
auto apply() -> const boxed&;
auto applyFirst() -> const boxed&;
auto applySecond() -> const boxed&;
auto lift2() -> const boxed&;
auto lift3() -> const boxed&;
auto lift4() -> const boxed&;
auto lift5() -> const boxed&;
auto arrayApply() -> const boxed&;

} // end namespace Control_Apply

#endif // Control_Apply_H

