// Generated by pscpp compiler

#ifndef Data_String_NonEmpty_Internal_H
#define Data_String_NonEmpty_Internal_H

#include "purescript.h"

namespace Data_String_NonEmpty_Internal {

using namespace purescript;

auto NonEmptyString() -> const boxed&;
auto NonEmptyReplacement() -> const boxed&;
auto MakeNonEmpty() -> const boxed&;
auto toUpper() -> const boxed&;
auto toString() -> const boxed&;
auto toLower() -> const boxed&;
auto showNonEmptyString() -> boxed;
auto showNonEmptyReplacement() -> boxed;
auto semigroupNonEmptyString() -> boxed;
auto semigroupNonEmptyReplacement() -> boxed;
auto replaceAll() -> const boxed&;
auto replace() -> const boxed&;
auto prependString() -> const boxed&;
auto ordNonEmptyString() -> boxed;
auto ordNonEmptyReplacement() -> boxed;
auto nonEmptyNonEmpty() -> const boxed&;
auto nes() -> const boxed&;
auto makeNonEmptyBad() -> const boxed&;
auto localeCompare() -> const boxed&;
auto liftS() -> const boxed&;
auto joinWith1() -> const boxed&;
auto joinWith() -> const boxed&;
auto join1With() -> const boxed&;
auto fromString() -> const boxed&;
auto stripPrefix() -> const boxed&;
auto stripSuffix() -> const boxed&;
auto trim() -> const boxed&;
auto unsafeFromString() -> const boxed&;
auto eqNonEmptyString() -> boxed;
auto eqNonEmptyReplacement() -> boxed;
auto contains() -> boxed;
auto appendString() -> const boxed&;

} // end namespace Data_String_NonEmpty_Internal

#endif // Data_String_NonEmpty_Internal_H

