// Generated by pscpp compiler

#ifndef Data_Array_ST_Iterator_H
#define Data_Array_ST_Iterator_H

#include "purescript.h"

namespace Data_Array_ST_Iterator {

using namespace purescript;

auto Iterator() -> const boxed&;
auto _peek_() -> const boxed&;
auto next() -> const boxed&;
auto pushWhile() -> const boxed&;
auto pushAll() -> boxed;
auto iterator() -> const boxed&;
auto iterate() -> const boxed&;
auto exhausted() -> boxed;

} // end namespace Data_Array_ST_Iterator

#endif // Data_Array_ST_Iterator_H

