// Generated by pscpp compiler

#ifndef Data_Function_H
#define Data_Function_H

#include "purescript.h"

namespace Data_Function {

using namespace purescript;

auto on() -> const boxed&;
auto flip() -> const boxed&;
auto _const_() -> const boxed&;
auto applyN() -> const boxed&;
auto applyFlipped() -> const boxed&;
auto apply() -> const boxed&;

} // end namespace Data_Function

#endif // Data_Function_H

