// Generated by pscpp compiler

#ifndef Data_Eq_H
#define Data_Eq_H

#include "purescript.h"

namespace Data_Eq {

using namespace purescript;

auto Eq() -> const boxed&;
auto Eq1() -> const boxed&;
auto EqRecord() -> const boxed&;
auto eqVoid() -> boxed;
auto eqUnit() -> boxed;
auto eqString() -> boxed;
auto eqRowNil() -> boxed;
auto eqRecord() -> const boxed&;
auto eqRec() -> const boxed&;
auto eqNumber() -> boxed;
auto eqInt() -> boxed;
auto eqChar() -> boxed;
auto eqBoolean() -> boxed;
auto eq1() -> const boxed&;
auto eq() -> const boxed&;
auto eqArray() -> const boxed&;
auto eq1Array() -> boxed;
auto eqRowCons() -> const boxed&;
auto notEq() -> const boxed&;
auto notEq1() -> const boxed&;
auto refEq() -> const boxed&;
auto eqArrayImpl() -> const boxed&;

} // end namespace Data_Eq

#endif // Data_Eq_H

