// Generated by pscpp compiler

#ifndef Data_Ring_H
#define Data_Ring_H

#include "purescript.h"

namespace Data_Ring {

using namespace purescript;

auto RingRecord() -> const boxed&;
auto Ring() -> const boxed&;
auto subRecord() -> const boxed&;
auto sub() -> const boxed&;
auto ringUnit() -> boxed;
auto ringRecordNil() -> boxed;
auto ringRecordCons() -> const boxed&;
auto ringRecord() -> const boxed&;
auto ringNumber() -> boxed;
auto ringInt() -> boxed;
auto ringFn() -> const boxed&;
auto negate() -> const boxed&;
auto intSub() -> const boxed&;
auto numSub() -> const boxed&;

} // end namespace Data_Ring

#endif // Data_Ring_H

