// Generated by pscpp compiler

#ifndef Control_Monad_Except_Trans_H
#define Control_Monad_Except_Trans_H

#include "purescript.h"

namespace Control_Monad_Except_Trans {

using namespace purescript;

auto ExceptT() -> const boxed&;
auto withExceptT() -> const boxed&;
auto runExceptT() -> const boxed&;
auto newtypeExceptT() -> boxed;
auto monadTransExceptT() -> boxed;
auto mapExceptT() -> const boxed&;
auto functorExceptT() -> const boxed&;
auto except() -> const boxed&;
auto monadExceptT() -> const boxed&;
auto bindExceptT() -> const boxed&;
auto applyExceptT() -> const boxed&;
auto applicativeExceptT() -> const boxed&;
auto monadAskExceptT() -> const boxed&;
auto monadReaderExceptT() -> const boxed&;
auto monadContExceptT() -> const boxed&;
auto monadEffectExceptT() -> const boxed&;
auto monadRecExceptT() -> const boxed&;
auto monadStateExceptT() -> const boxed&;
auto monadTellExceptT() -> const boxed&;
auto monadWriterExceptT() -> const boxed&;
auto monadThrowExceptT() -> const boxed&;
auto monadErrorExceptT() -> const boxed&;
auto altExceptT() -> const boxed&;
auto plusExceptT() -> const boxed&;
auto alternativeExceptT() -> const boxed&;
auto monadZeroExceptT() -> const boxed&;
auto monadPlusExceptT() -> const boxed&;

} // end namespace Control_Monad_Except_Trans

#endif // Control_Monad_Except_Trans_H

