// Generated by pscpp compiler

#ifndef Control_Monad_RWS_H
#define Control_Monad_RWS_H

#include "purescript.h"

namespace Control_Monad_RWS {

using namespace purescript;

auto withRWS() -> boxed;
auto rws() -> const boxed&;
auto runRWS() -> const boxed&;
auto mapRWS() -> const boxed&;
auto execRWS() -> const boxed&;
auto evalRWS() -> const boxed&;

} // end namespace Control_Monad_RWS

#endif // Control_Monad_RWS_H

