// Generated by pscpp compiler

#ifndef Control_Bind_H
#define Control_Bind_H

#include "purescript.h"

namespace Control_Bind {

using namespace purescript;

auto Discard() -> const boxed&;
auto Bind() -> const boxed&;
auto discard() -> const boxed&;
auto bindFn() -> boxed;
auto bindArray() -> boxed;
auto bind() -> const boxed&;
auto bindFlipped() -> const boxed&;
auto composeKleisliFlipped() -> const boxed&;
auto composeKleisli() -> const boxed&;
auto discardUnit() -> boxed;
auto ifM() -> const boxed&;
auto join() -> const boxed&;
auto arrayBind() -> const boxed&;

} // end namespace Control_Bind

#endif // Control_Bind_H

