// Generated by pscpp compiler

#ifndef Partial_H
#define Partial_H

#include "purescript.h"

namespace Partial {

using namespace purescript;

auto crash() -> const boxed&;
auto crashWith() -> const boxed&;

} // end namespace Partial

#endif // Partial_H

