// Generated by pscpp compiler

#ifndef Control_Monad_Reader_Trans_H
#define Control_Monad_Reader_Trans_H

#include "purescript.h"

namespace Control_Monad_Reader_Trans {

using namespace purescript;

auto ReaderT() -> const boxed&;
auto withReaderT() -> const boxed&;
auto runReaderT() -> const boxed&;
auto newtypeReaderT() -> boxed;
auto monadTransReaderT() -> boxed;
auto mapReaderT() -> const boxed&;
auto functorReaderT() -> const boxed&;
auto distributiveReaderT() -> const boxed&;
auto applyReaderT() -> const boxed&;
auto bindReaderT() -> const boxed&;
auto semigroupReaderT() -> const boxed&;
auto applicativeReaderT() -> const boxed&;
auto monadReaderT() -> const boxed&;
auto monadAskReaderT() -> const boxed&;
auto monadReaderReaderT() -> const boxed&;
auto monadContReaderT() -> const boxed&;
auto monadEffectReader() -> const boxed&;
auto monadRecReaderT() -> const boxed&;
auto monadStateReaderT() -> const boxed&;
auto monadTellReaderT() -> const boxed&;
auto monadWriterReaderT() -> const boxed&;
auto monadThrowReaderT() -> const boxed&;
auto monadErrorReaderT() -> const boxed&;
auto monoidReaderT() -> const boxed&;
auto altReaderT() -> const boxed&;
auto plusReaderT() -> const boxed&;
auto alternativeReaderT() -> const boxed&;
auto monadZeroReaderT() -> const boxed&;
auto monadPlusReaderT() -> const boxed&;

} // end namespace Control_Monad_Reader_Trans

#endif // Control_Monad_Reader_Trans_H

