// Generated by pscpp compiler

#ifndef Effect_Exception_Unsafe_H
#define Effect_Exception_Unsafe_H

#include "purescript.h"

namespace Effect_Exception_Unsafe {

using namespace purescript;

auto unsafeThrowException() -> boxed;
auto unsafeThrow() -> boxed;

} // end namespace Effect_Exception_Unsafe

#endif // Effect_Exception_Unsafe_H

