// Generated by pscpp compiler

#ifndef Control_Monad_ST_H
#define Control_Monad_ST_H

#include "purescript.h"

namespace Control_Monad_ST {

using namespace purescript;


} // end namespace Control_Monad_ST

#endif // Control_Monad_ST_H

