// Generated by pscpp compiler

#ifndef Control_Comonad_Env_Trans_H
#define Control_Comonad_Env_Trans_H

#include "purescript.h"

namespace Control_Comonad_Env_Trans {

using namespace purescript;

auto EnvT() -> const boxed&;
auto withEnvT() -> const boxed&;
auto runEnvT() -> const boxed&;
auto newtypeEnvT() -> boxed;
auto mapEnvT() -> const boxed&;
auto functorEnvT() -> const boxed&;
auto foldableEnvT() -> const boxed&;
auto traversableEnvT() -> const boxed&;
auto extendEnvT() -> const boxed&;
auto comonadTransEnvT() -> boxed;
auto comonadEnvT() -> const boxed&;

} // end namespace Control_Comonad_Env_Trans

#endif // Control_Comonad_Env_Trans_H

