// Generated by pscpp compiler

#ifndef Effect_Console_H
#define Effect_Console_H

#include "purescript.h"

namespace Effect_Console {

using namespace purescript;

auto warnShow() -> const boxed&;
auto logShow() -> const boxed&;
auto infoShow() -> const boxed&;
auto errorShow() -> const boxed&;
auto log() -> const boxed&;
auto warn() -> const boxed&;
auto error() -> const boxed&;
auto info() -> const boxed&;
auto time() -> const boxed&;
auto timeEnd() -> const boxed&;

} // end namespace Effect_Console

#endif // Effect_Console_H

