// Generated by pscpp compiler

#ifndef Test_Main_H
#define Test_Main_H

#include "purescript.h"

namespace Test_Main {

using namespace purescript;

auto plusInfinity() -> boxed;
auto nan() -> boxed;
auto minusInfinity() -> boxed;
auto _assert_() -> const boxed&;
auto testIntDegree() -> boxed;
auto testIntDivMod() -> boxed;
auto testOrd() -> const boxed&;
auto testOrdUtils() -> boxed;
auto testOrderings() -> boxed;
auto testRecordInstances() -> boxed;
auto main() -> boxed;
auto testNumberShow() -> const boxed&;
auto throwErr() -> const boxed&;

} // end namespace Test_Main

#endif // Test_Main_H

