// Generated by pscpp compiler

#ifndef Data_String_Common_H
#define Data_String_Common_H

#include "purescript.h"

namespace Data_String_Common {

using namespace purescript;

auto null() -> const boxed&;
auto localeCompare() -> boxed;
auto _localeCompare() -> const boxed&;
auto replace() -> const boxed&;
auto replaceAll() -> const boxed&;
auto split() -> const boxed&;
auto toLower() -> const boxed&;
auto toUpper() -> const boxed&;
auto trim() -> const boxed&;
auto joinWith() -> const boxed&;

} // end namespace Data_String_Common

#endif // Data_String_Common_H

