// Generated by pscpp compiler

#ifndef Data_Traversable_Accum_H
#define Data_Traversable_Accum_H

#include "purescript.h"

namespace Data_Traversable_Accum {

using namespace purescript;


} // end namespace Data_Traversable_Accum

#endif // Data_Traversable_Accum_H

