// Generated by pscpp compiler

#ifndef Data_Traversable_H
#define Data_Traversable_H

#include "purescript.h"

namespace Data_Traversable {

using namespace purescript;

auto Traversable() -> const boxed&;
auto traverse() -> const boxed&;
auto traversableMultiplicative() -> boxed;
auto traversableMaybe() -> boxed;
auto traversableDual() -> boxed;
auto traversableDisj() -> boxed;
auto traversableConj() -> boxed;
auto traversableAdditive() -> boxed;
auto sequenceDefault() -> const boxed&;
auto traversableArray() -> boxed;
auto sequence() -> const boxed&;
auto traversableFirst() -> boxed;
auto traversableLast() -> boxed;
auto traverseDefault() -> const boxed&;
auto mapAccumR() -> const boxed&;
auto scanr() -> const boxed&;
auto mapAccumL() -> const boxed&;
auto scanl() -> const boxed&;
auto _for_() -> const boxed&;
auto traverseArrayImpl() -> const boxed&;

} // end namespace Data_Traversable

#endif // Data_Traversable_H

