// Generated by pscpp compiler

#ifndef Data_Semigroup_Last_H
#define Data_Semigroup_Last_H

#include "purescript.h"

namespace Data_Semigroup_Last {

using namespace purescript;

auto Last() -> const boxed&;
auto showLast() -> const boxed&;
auto semigroupLast() -> boxed;
auto ordLast() -> const boxed&;
auto functorLast() -> boxed;
auto eqLast() -> const boxed&;
auto eq1Last() -> boxed;
auto ord1Last() -> boxed;
auto boundedLast() -> const boxed&;
auto applyLast() -> boxed;
auto bindLast() -> boxed;
auto applicativeLast() -> boxed;
auto monadLast() -> boxed;

} // end namespace Data_Semigroup_Last

#endif // Data_Semigroup_Last_H

