// Generated by pscpp compiler

#ifndef Data_TraversableWithIndex_H
#define Data_TraversableWithIndex_H

#include "purescript.h"

namespace Data_TraversableWithIndex {

using namespace purescript;

auto TraversableWithIndex() -> const boxed&;
auto traverseWithIndexDefault() -> const boxed&;
auto traverseWithIndex() -> const boxed&;
auto traverseDefault() -> const boxed&;
auto traversableWithIndexMultiplicative() -> boxed;
auto traversableWithIndexMaybe() -> boxed;
auto traversableWithIndexLast() -> boxed;
auto traversableWithIndexFirst() -> boxed;
auto traversableWithIndexDual() -> boxed;
auto traversableWithIndexDisj() -> boxed;
auto traversableWithIndexConj() -> boxed;
auto traversableWithIndexArray() -> boxed;
auto traversableWithIndexAdditive() -> boxed;
auto mapAccumRWithIndex() -> const boxed&;
auto scanrWithIndex() -> const boxed&;
auto mapAccumLWithIndex() -> const boxed&;
auto scanlWithIndex() -> const boxed&;
auto forWithIndex() -> const boxed&;

} // end namespace Data_TraversableWithIndex

#endif // Data_TraversableWithIndex_H

