// Generated by pscpp compiler

#ifndef Data_Maybe_H
#define Data_Maybe_H

#include "purescript.h"

namespace Data_Maybe {

using namespace purescript;

auto Nothing() -> const boxed&;
auto Just() -> const boxed&;
auto showMaybe() -> const boxed&;
auto semigroupMaybe() -> const boxed&;
auto optional() -> const boxed&;
auto monoidMaybe() -> const boxed&;
auto maybe_Prime_() -> const boxed&;
auto maybe() -> const boxed&;
auto isNothing() -> boxed;
auto isJust() -> boxed;
auto functorMaybe() -> boxed;
auto invariantMaybe() -> boxed;
auto fromMaybe_Prime_() -> const boxed&;
auto fromMaybe() -> const boxed&;
auto fromJust() -> const boxed&;
auto extendMaybe() -> boxed;
auto eqMaybe() -> const boxed&;
auto ordMaybe() -> const boxed&;
auto eq1Maybe() -> boxed;
auto ord1Maybe() -> boxed;
auto boundedMaybe() -> const boxed&;
auto applyMaybe() -> boxed;
auto bindMaybe() -> boxed;
auto applicativeMaybe() -> boxed;
auto monadMaybe() -> boxed;
auto altMaybe() -> boxed;
auto plusMaybe() -> boxed;
auto alternativeMaybe() -> boxed;
auto monadZeroMaybe() -> boxed;

} // end namespace Data_Maybe

#endif // Data_Maybe_H

