// Generated by pscpp compiler

#ifndef Control_Comonad_Store_H
#define Control_Comonad_Store_H

#include "purescript.h"

namespace Control_Comonad_Store {

using namespace purescript;

auto store() -> const boxed&;
auto runStore() -> const boxed&;

} // end namespace Control_Comonad_Store

#endif // Control_Comonad_Store_H

