// Generated by pscpp compiler

#ifndef Data_Boolean_H
#define Data_Boolean_H

#include "purescript.h"

namespace Data_Boolean {

using namespace purescript;

auto otherwise() -> const boxed&;

} // end namespace Data_Boolean

#endif // Data_Boolean_H

