// Generated by pscpp compiler

#ifndef Control_Monad_Reader_Class_H
#define Control_Monad_Reader_Class_H

#include "purescript.h"

namespace Control_Monad_Reader_Class {

using namespace purescript;

auto MonadAsk() -> const boxed&;
auto MonadReader() -> const boxed&;
auto monadAskFun() -> boxed;
auto monadReaderFun() -> boxed;
auto local() -> const boxed&;
auto ask() -> const boxed&;
auto asks() -> const boxed&;

} // end namespace Control_Monad_Reader_Class

#endif // Control_Monad_Reader_Class_H

