// Generated by pscpp compiler

#ifndef Data_Show_H
#define Data_Show_H

#include "purescript.h"

namespace Data_Show {

using namespace purescript;

auto ShowRecordFields() -> const boxed&;
auto Show() -> const boxed&;
auto showString() -> boxed;
auto showRecordFieldsNil() -> boxed;
auto showRecordFields() -> const boxed&;
auto showRecord() -> const boxed&;
auto showNumber() -> boxed;
auto showInt() -> boxed;
auto showChar() -> boxed;
auto showBoolean() -> boxed;
auto show() -> const boxed&;
auto showArray() -> const boxed&;
auto showRecordFieldsCons() -> const boxed&;
auto showIntImpl() -> const boxed&;
auto showNumberImpl() -> const boxed&;
auto showCharImpl() -> const boxed&;
auto showStringImpl() -> const boxed&;
auto showArrayImpl() -> const boxed&;
auto cons() -> const boxed&;
auto join() -> const boxed&;

} // end namespace Data_Show

#endif // Data_Show_H

