// Generated by pscpp compiler

#ifndef Control_Monad_Maybe_Trans_H
#define Control_Monad_Maybe_Trans_H

#include "purescript.h"

namespace Control_Monad_Maybe_Trans {

using namespace purescript;

auto MaybeT() -> const boxed&;
auto runMaybeT() -> const boxed&;
auto newtypeMaybeT() -> boxed;
auto monadTransMaybeT() -> boxed;
auto mapMaybeT() -> const boxed&;
auto functorMaybeT() -> const boxed&;
auto monadMaybeT() -> const boxed&;
auto bindMaybeT() -> const boxed&;
auto applyMaybeT() -> const boxed&;
auto applicativeMaybeT() -> const boxed&;
auto monadAskMaybeT() -> const boxed&;
auto monadReaderMaybeT() -> const boxed&;
auto monadContMaybeT() -> const boxed&;
auto monadEffectMaybe() -> const boxed&;
auto monadRecMaybeT() -> const boxed&;
auto monadStateMaybeT() -> const boxed&;
auto monadTellMaybeT() -> const boxed&;
auto monadWriterMaybeT() -> const boxed&;
auto monadThrowMaybeT() -> const boxed&;
auto monadErrorMaybeT() -> const boxed&;
auto altMaybeT() -> const boxed&;
auto plusMaybeT() -> const boxed&;
auto alternativeMaybeT() -> const boxed&;
auto monadZeroMaybeT() -> const boxed&;
auto monadPlusMaybeT() -> const boxed&;

} // end namespace Control_Monad_Maybe_Trans

#endif // Control_Monad_Maybe_Trans_H

