// Generated by pscpp compiler

#ifndef Data_Unfoldable_H
#define Data_Unfoldable_H

#include "purescript.h"

namespace Data_Unfoldable {

using namespace purescript;

auto Unfoldable() -> const boxed&;
auto unfoldr() -> const boxed&;
auto unfoldableArray() -> boxed;
auto replicate() -> const boxed&;
auto replicateA() -> const boxed&;
auto none() -> const boxed&;
auto fromMaybe() -> const boxed&;
auto unfoldrArrayImpl() -> const boxed&;

} // end namespace Data_Unfoldable

#endif // Data_Unfoldable_H

