// Generated by pscpp compiler

#ifndef Data_String_Regex_Unsafe_H
#define Data_String_Regex_Unsafe_H

#include "purescript.h"

namespace Data_String_Regex_Unsafe {

using namespace purescript;

auto unsafeRegex() -> const boxed&;

} // end namespace Data_String_Regex_Unsafe

#endif // Data_String_Regex_Unsafe_H

