// Generated by pscpp compiler

#ifndef Data_Maybe_First_H
#define Data_Maybe_First_H

#include "purescript.h"

namespace Data_Maybe_First {

using namespace purescript;

auto First() -> const boxed&;
auto showFirst() -> const boxed&;
auto semigroupFirst() -> boxed;
auto ordFirst() -> const boxed&;
auto ord1First() -> boxed;
auto newtypeFirst() -> boxed;
auto monoidFirst() -> boxed;
auto monadFirst() -> boxed;
auto invariantFirst() -> boxed;
auto functorFirst() -> boxed;
auto extendFirst() -> boxed;
auto eqFirst() -> const boxed&;
auto eq1First() -> boxed;
auto boundedFirst() -> const boxed&;
auto bindFirst() -> boxed;
auto applyFirst() -> boxed;
auto applicativeFirst() -> boxed;
auto altFirst() -> boxed;
auto plusFirst() -> boxed;
auto alternativeFirst() -> boxed;
auto monadZeroFirst() -> boxed;

} // end namespace Data_Maybe_First

#endif // Data_Maybe_First_H

