// Generated by pscpp compiler

#ifndef Data_Monoid_Conj_H
#define Data_Monoid_Conj_H

#include "purescript.h"

namespace Data_Monoid_Conj {

using namespace purescript;

auto Conj() -> const boxed&;
auto showConj() -> const boxed&;
auto semiringConj() -> const boxed&;
auto semigroupConj() -> const boxed&;
auto ordConj() -> const boxed&;
auto monoidConj() -> const boxed&;
auto functorConj() -> boxed;
auto eqConj() -> const boxed&;
auto eq1Conj() -> boxed;
auto ord1Conj() -> boxed;
auto boundedConj() -> const boxed&;
auto applyConj() -> boxed;
auto bindConj() -> boxed;
auto applicativeConj() -> boxed;
auto monadConj() -> boxed;

} // end namespace Data_Monoid_Conj

#endif // Data_Monoid_Conj_H

