// Generated by pscpp compiler

#ifndef Data_NaturalTransformation_H
#define Data_NaturalTransformation_H

#include "purescript.h"

namespace Data_NaturalTransformation {

using namespace purescript;


} // end namespace Data_NaturalTransformation

#endif // Data_NaturalTransformation_H

