// Generated by pscpp compiler

#ifndef Data_Array_ST_Partial_H
#define Data_Array_ST_Partial_H

#include "purescript.h"

namespace Data_Array_ST_Partial {

using namespace purescript;

auto poke() -> const boxed&;
auto _peek_() -> const boxed&;
auto peekImpl() -> const boxed&;
auto pokeImpl() -> const boxed&;

} // end namespace Data_Array_ST_Partial

#endif // Data_Array_ST_Partial_H

