// Generated by pscpp compiler

#ifndef Text_Parsing_Parser_Combinators_H
#define Text_Parsing_Parser_Combinators_H

#include "purescript.h"

namespace Text_Parsing_Parser_Combinators {

using namespace purescript;

auto withErrorMessage() -> const boxed&;
auto tryRethrow() -> const boxed&;
auto _try_() -> const boxed&;
auto skipMany1() -> const boxed&;
auto skipMany() -> const boxed&;
auto sepEndBy1() -> const boxed&;
auto sepEndBy() -> const boxed&;
auto sepBy1() -> const boxed&;
auto sepBy() -> const boxed&;
auto optional() -> const boxed&;
auto option() -> const boxed&;
auto optionMaybe() -> const boxed&;
auto notFollowedBy() -> const boxed&;
auto manyTill() -> const boxed&;
auto many1Till() -> const boxed&;
auto lookAhead() -> const boxed&;
auto endBy1() -> const boxed&;
auto endBy() -> const boxed&;
auto choice() -> const boxed&;
auto chainr1_Prime_() -> const boxed&;
auto chainr1() -> const boxed&;
auto chainr() -> const boxed&;
auto chainl1_Prime_() -> const boxed&;
auto chainl1() -> const boxed&;
auto chainl() -> const boxed&;
auto between() -> const boxed&;
auto asErrorMessage() -> const boxed&;

} // end namespace Text_Parsing_Parser_Combinators

#endif // Text_Parsing_Parser_Combinators_H

