// Generated by pscpp compiler

#ifndef Control_Comonad_Env_H
#define Control_Comonad_Env_H

#include "purescript.h"

namespace Control_Comonad_Env {

using namespace purescript;

auto withEnv() -> boxed;
auto runEnv() -> const boxed&;
auto mapEnv() -> boxed;
auto env() -> const boxed&;

} // end namespace Control_Comonad_Env

#endif // Control_Comonad_Env_H

