// Generated by pscpp compiler

#ifndef Data_HeytingAlgebra_H
#define Data_HeytingAlgebra_H

#include "purescript.h"

namespace Data_HeytingAlgebra {

using namespace purescript;

auto HeytingAlgebraRecord() -> const boxed&;
auto HeytingAlgebra() -> const boxed&;
auto ttRecord() -> const boxed&;
auto tt() -> const boxed&;
auto notRecord() -> const boxed&;
auto _not_() -> const boxed&;
auto impliesRecord() -> const boxed&;
auto implies() -> const boxed&;
auto heytingAlgebraUnit() -> boxed;
auto heytingAlgebraRecordNil() -> boxed;
auto ffRecord() -> const boxed&;
auto ff() -> const boxed&;
auto disjRecord() -> const boxed&;
auto disj() -> const boxed&;
auto heytingAlgebraBoolean() -> boxed;
auto conjRecord() -> const boxed&;
auto heytingAlgebraRecord() -> const boxed&;
auto conj() -> const boxed&;
auto heytingAlgebraFunction() -> const boxed&;
auto heytingAlgebraRecordCons() -> const boxed&;
auto boolConj() -> const boxed&;
auto boolDisj() -> const boxed&;
auto boolNot() -> const boxed&;

} // end namespace Data_HeytingAlgebra

#endif // Data_HeytingAlgebra_H

