// Generated by pscpp compiler

#ifndef Data_Bifunctor_Clown_H
#define Data_Bifunctor_Clown_H

#include "purescript.h"

namespace Data_Bifunctor_Clown {

using namespace purescript;

auto Clown() -> const boxed&;
auto showClown() -> const boxed&;
auto ordClown() -> const boxed&;
auto newtypeClown() -> boxed;
auto functorClown() -> boxed;
auto eqClown() -> const boxed&;
auto bifunctorClown() -> const boxed&;
auto biapplyClown() -> const boxed&;
auto biapplicativeClown() -> const boxed&;

} // end namespace Data_Bifunctor_Clown

#endif // Data_Bifunctor_Clown_H

