// Generated by pscpp compiler

#ifndef Control_Applicative_H
#define Control_Applicative_H

#include "purescript.h"

namespace Control_Applicative {

using namespace purescript;

auto Applicative() -> const boxed&;
auto pure() -> const boxed&;
auto unless() -> const boxed&;
auto when() -> const boxed&;
auto liftA1() -> const boxed&;
auto applicativeFn() -> boxed;
auto applicativeArray() -> boxed;

} // end namespace Control_Applicative

#endif // Control_Applicative_H

