// Generated by pscpp compiler

#ifndef Control_Monad_State_Trans_H
#define Control_Monad_State_Trans_H

#include "purescript.h"

namespace Control_Monad_State_Trans {

using namespace purescript;

auto StateT() -> const boxed&;
auto withStateT() -> const boxed&;
auto runStateT() -> const boxed&;
auto newtypeStateT() -> boxed;
auto monadTransStateT() -> boxed;
auto mapStateT() -> const boxed&;
auto lazyStateT() -> boxed;
auto functorStateT() -> const boxed&;
auto execStateT() -> const boxed&;
auto evalStateT() -> const boxed&;
auto monadStateT() -> const boxed&;
auto bindStateT() -> const boxed&;
auto applyStateT() -> const boxed&;
auto applicativeStateT() -> const boxed&;
auto monadAskStateT() -> const boxed&;
auto monadReaderStateT() -> const boxed&;
auto monadContStateT() -> const boxed&;
auto monadEffectState() -> const boxed&;
auto monadRecStateT() -> const boxed&;
auto monadStateStateT() -> const boxed&;
auto monadTellStateT() -> const boxed&;
auto monadWriterStateT() -> const boxed&;
auto monadThrowStateT() -> const boxed&;
auto monadErrorStateT() -> const boxed&;
auto altStateT() -> const boxed&;
auto plusStateT() -> const boxed&;
auto alternativeStateT() -> const boxed&;
auto monadZeroStateT() -> const boxed&;
auto monadPlusStateT() -> const boxed&;

} // end namespace Control_Monad_State_Trans

#endif // Control_Monad_State_Trans_H

