// Generated by pscpp compiler

#ifndef Text_Parsing_Parser_H
#define Text_Parsing_Parser_H

#include "purescript.h"

namespace Text_Parsing_Parser {

using namespace purescript;

auto ParseState() -> const boxed&;
auto ParseError() -> const boxed&;
auto ParserT() -> const boxed&;
auto showParseError() -> boxed;
auto parseErrorPosition() -> const boxed&;
auto parseErrorMessage() -> const boxed&;
auto newtypeParserT() -> boxed;
auto runParserT() -> const boxed&;
auto runParser() -> const boxed&;
auto monadTransParserT() -> boxed;
auto monadThrowParserT() -> const boxed&;
auto monadStateParserT() -> const boxed&;
auto position() -> const boxed&;
auto monadRecParserT() -> const boxed&;
auto monadParserT() -> const boxed&;
auto monadErrorParserT() -> const boxed&;
auto mapParserT() -> boxed;
auto lazyParserT() -> boxed;
auto hoistParserT() -> boxed;
auto functorParserT() -> const boxed&;
auto failWithPosition() -> const boxed&;
auto eqParseError() -> boxed;
auto ordParseError() -> boxed;
auto consume() -> const boxed&;
auto bindParserT() -> const boxed&;
auto fail() -> const boxed&;
auto applyParserT() -> const boxed&;
auto semigroupParserT() -> const boxed&;
auto applicativeParserT() -> const boxed&;
auto monoidParserT() -> const boxed&;
auto altParserT() -> const boxed&;
auto plusParserT() -> const boxed&;
auto alternativeParserT() -> const boxed&;
auto monadZeroParserT() -> const boxed&;
auto monadPlusParserT() -> const boxed&;

} // end namespace Text_Parsing_Parser

#endif // Text_Parsing_Parser_H

