// Generated by pscpp compiler

#ifndef Data_List_Types_H
#define Data_List_Types_H

#include "purescript.h"

namespace Data_List_Types {

using namespace purescript;

auto Nil() -> const boxed&;
auto Cons() -> const boxed&;
auto NonEmptyList() -> const boxed&;
auto toList() -> const boxed&;
auto newtypeNonEmptyList() -> boxed;
auto nelCons() -> const boxed&;
auto foldableList() -> boxed;
auto foldableNonEmptyList() -> boxed;
auto foldableWithIndexList() -> boxed;
auto foldableWithIndexNonEmptyList() -> boxed;
auto functorList() -> boxed;
auto functorNonEmptyList() -> boxed;
auto functorWithIndexList() -> boxed;
auto functorWithIndexNonEmptyList() -> boxed;
auto semigroupList() -> boxed;
auto monoidList() -> boxed;
auto semigroupNonEmptyList() -> boxed;
auto showList() -> const boxed&;
auto showNonEmptyList() -> const boxed&;
auto traversableList() -> boxed;
auto traversableNonEmptyList() -> boxed;
auto traversableWithIndexList() -> boxed;
auto traversableWithIndexNonEmptyList() -> boxed;
auto unfoldable1List() -> boxed;
auto unfoldableList() -> boxed;
auto unfoldable1NonEmptyList() -> boxed;
auto foldable1NonEmptyList() -> boxed;
auto extendNonEmptyList() -> boxed;
auto extendList() -> boxed;
auto eq1List() -> boxed;
auto eqList() -> const boxed&;
auto eqNonEmptyList() -> const boxed&;
auto ord1List() -> boxed;
auto ordList() -> const boxed&;
auto ordNonEmptyList() -> const boxed&;
auto comonadNonEmptyList() -> boxed;
auto applyList() -> boxed;
auto applyNonEmptyList() -> boxed;
auto bindList() -> boxed;
auto bindNonEmptyList() -> boxed;
auto applicativeList() -> boxed;
auto monadList() -> boxed;
auto altNonEmptyList() -> boxed;
auto altList() -> boxed;
auto plusList() -> boxed;
auto alternativeList() -> boxed;
auto monadZeroList() -> boxed;
auto monadPlusList() -> boxed;
auto applicativeNonEmptyList() -> boxed;
auto monadNonEmptyList() -> boxed;
auto traversable1NonEmptyList() -> boxed;

} // end namespace Data_List_Types

#endif // Data_List_Types_H

