// Generated by pscpp compiler

#ifndef Control_Alternative_H
#define Control_Alternative_H

#include "purescript.h"

namespace Control_Alternative {

using namespace purescript;

auto Alternative() -> const boxed&;
auto alternativeArray() -> boxed;

} // end namespace Control_Alternative

#endif // Control_Alternative_H

