// Generated by pscpp compiler

#ifndef Control_Monad_ST_Internal_H
#define Control_Monad_ST_Internal_H

#include "purescript.h"

namespace Control_Monad_ST_Internal {

using namespace purescript;

auto modify() -> const boxed&;
auto functorST() -> boxed;
auto monadST() -> boxed;
auto bindST() -> boxed;
auto applyST() -> boxed;
auto applicativeST() -> boxed;
auto monadRecST() -> boxed;
auto map_() -> const boxed&;
auto pure_() -> const boxed&;
auto bind_() -> const boxed&;
auto run() -> const boxed&;
auto _while_() -> const boxed&;
auto _for_() -> const boxed&;
auto foreach() -> const boxed&;
auto _new_() -> const boxed&;
auto read() -> const boxed&;
auto modify_Prime_() -> const boxed&;
auto write() -> const boxed&;

} // end namespace Control_Monad_ST_Internal

#endif // Control_Monad_ST_Internal_H

