// Generated by pscpp compiler

#ifndef Main_H
#define Main_H

#include "purescript.h"

namespace Main {

using namespace purescript;

auto factorial() -> const boxed&;
auto main() -> const boxed&;

} // end namespace Main

#endif // Main_H

