// Generated by pscpp compiler

#ifndef Main_H
#define Main_H

#include "purescript.h"

namespace Main {

using namespace purescript;

auto Kill() -> const boxed&;
auto showKill() -> boxed;
auto s1() -> const boxed&;
auto parseTest() -> const boxed&;
auto parens() -> boxed;
auto parseNameNum() -> boxed;
auto opTest() -> boxed;
auto notFollowedBy() -> const boxed&;
auto main() -> boxed;
auto factorial() -> const boxed&;

} // end namespace Main

#endif // Main_H

