// Generated by pscpp compiler

#ifndef Main_H
#define Main_H

#include "purescript.h"

namespace Main {

using namespace purescript;

auto Kill() -> const boxed&;
auto s1() -> const boxed&;
auto parseTest() -> const boxed&;
auto parseSingleDigitInt() -> boxed;
auto parens() -> const boxed&;
auto opTest() -> boxed;
auto main() -> const boxed&;
auto factorial() -> const boxed&;

} // end namespace Main

#endif // Main_H

