// Generated by pscpp compiler

#ifndef Data_Bifunctor_Join_H
#define Data_Bifunctor_Join_H

#include "purescript.h"

namespace Data_Bifunctor_Join {

using namespace purescript;

auto Join() -> const boxed&;
auto showJoin() -> const boxed&;
auto ordJoin() -> const boxed&;
auto newtypeJoin() -> boxed;
auto eqJoin() -> const boxed&;
auto bifunctorJoin() -> const boxed&;
auto biapplyJoin() -> const boxed&;
auto biapplicativeJoin() -> const boxed&;

} // end namespace Data_Bifunctor_Join

#endif // Data_Bifunctor_Join_H

