// Generated by pscpp compiler

#ifndef Effect_Uncurried_H
#define Effect_Uncurried_H

#include "purescript.h"

namespace Effect_Uncurried {

using namespace purescript;

auto mkEffectFn1() -> const boxed&;
auto mkEffectFn2() -> const boxed&;
auto mkEffectFn3() -> const boxed&;
auto mkEffectFn4() -> const boxed&;
auto mkEffectFn5() -> const boxed&;
auto mkEffectFn6() -> const boxed&;
auto mkEffectFn7() -> const boxed&;
auto mkEffectFn8() -> const boxed&;
auto mkEffectFn9() -> const boxed&;
auto mkEffectFn10() -> const boxed&;
auto runEffectFn1() -> const boxed&;
auto runEffectFn2() -> const boxed&;
auto runEffectFn3() -> const boxed&;
auto runEffectFn4() -> const boxed&;
auto runEffectFn5() -> const boxed&;
auto runEffectFn6() -> const boxed&;
auto runEffectFn7() -> const boxed&;
auto runEffectFn8() -> const boxed&;
auto runEffectFn9() -> const boxed&;
auto runEffectFn10() -> const boxed&;

} // end namespace Effect_Uncurried

#endif // Effect_Uncurried_H

