// Generated by pscpp compiler

#ifndef Data_String_NonEmpty_CodePoints_H
#define Data_String_NonEmpty_CodePoints_H

#include "purescript.h"

namespace Data_String_NonEmpty_CodePoints {

using namespace purescript;

auto toNonEmptyString() -> boxed;
auto snoc() -> const boxed&;
auto singleton() -> boxed;
auto liftS() -> boxed;
auto takeWhile() -> const boxed&;
auto lastIndexOf_Prime_() -> const boxed&;
auto lastIndexOf() -> boxed;
auto indexOf_Prime_() -> const boxed&;
auto indexOf() -> boxed;
auto fromNonEmptyString() -> boxed;
auto length() -> boxed;
auto splitAt() -> const boxed&;
auto take() -> const boxed&;
auto toCodePointArray() -> boxed;
auto toNonEmptyCodePointArray() -> boxed;
auto uncons() -> const boxed&;
auto fromFoldable1() -> const boxed&;
auto fromCodePointArray() -> const boxed&;
auto fromNonEmptyCodePointArray() -> boxed;
auto dropWhile() -> const boxed&;
auto drop() -> const boxed&;
auto countPrefix() -> boxed;
auto cons() -> const boxed&;
auto codePointAt() -> boxed;

} // end namespace Data_String_NonEmpty_CodePoints

#endif // Data_String_NonEmpty_CodePoints_H

