// Generated by pscpp compiler

#ifndef Data_Array_ST_H
#define Data_Array_ST_H

#include "purescript.h"

namespace Data_Array_ST {

using namespace purescript;

auto unsafeThaw() -> boxed;
auto unsafeFreeze() -> boxed;
auto thaw() -> boxed;
auto withArray() -> const boxed&;
auto sortBy() -> const boxed&;
auto sortWith() -> const boxed&;
auto sort() -> const boxed&;
auto run() -> const boxed&;
auto push() -> const boxed&;
auto _peek_() -> boxed;
auto modify() -> const boxed&;
auto freeze() -> boxed;
auto empty() -> const boxed&;
auto sortByImpl() -> const boxed&;
auto copyImpl() -> const boxed&;
auto peekImpl() -> const boxed&;
auto poke() -> const boxed&;
auto pushAll() -> const boxed&;
auto splice() -> const boxed&;
auto toAssocArray() -> const boxed&;

} // end namespace Data_Array_ST

#endif // Data_Array_ST_H

