// Generated by pscpp compiler

#ifndef Data_Bifunctor_Joker_H
#define Data_Bifunctor_Joker_H

#include "purescript.h"

namespace Data_Bifunctor_Joker {

using namespace purescript;

auto Joker() -> const boxed&;
auto showJoker() -> const boxed&;
auto ordJoker() -> const boxed&;
auto newtypeJoker() -> boxed;
auto functorJoker() -> const boxed&;
auto eqJoker() -> const boxed&;
auto bifunctorJoker() -> const boxed&;
auto biapplyJoker() -> const boxed&;
auto biapplicativeJoker() -> const boxed&;

} // end namespace Data_Bifunctor_Joker

#endif // Data_Bifunctor_Joker_H

