// Generated by pscpp compiler

#ifndef Data_Monoid_Multiplicative_H
#define Data_Monoid_Multiplicative_H

#include "purescript.h"

namespace Data_Monoid_Multiplicative {

using namespace purescript;

auto Multiplicative() -> const boxed&;
auto showMultiplicative() -> const boxed&;
auto semigroupMultiplicative() -> const boxed&;
auto ordMultiplicative() -> const boxed&;
auto monoidMultiplicative() -> const boxed&;
auto functorMultiplicative() -> boxed;
auto eqMultiplicative() -> const boxed&;
auto eq1Multiplicative() -> boxed;
auto ord1Multiplicative() -> boxed;
auto boundedMultiplicative() -> const boxed&;
auto applyMultiplicative() -> boxed;
auto bindMultiplicative() -> boxed;
auto applicativeMultiplicative() -> boxed;
auto monadMultiplicative() -> boxed;

} // end namespace Data_Monoid_Multiplicative

#endif // Data_Monoid_Multiplicative_H

