// Generated by pscpp compiler

#ifndef Data_Traversable_Accum_Internal_H
#define Data_Traversable_Accum_Internal_H

#include "purescript.h"

namespace Data_Traversable_Accum_Internal {

using namespace purescript;

auto StateR() -> const boxed&;
auto StateL() -> const boxed&;
auto stateR() -> const boxed&;
auto stateL() -> const boxed&;
auto functorStateR() -> boxed;
auto functorStateL() -> boxed;
auto applyStateR() -> boxed;
auto applyStateL() -> boxed;
auto applicativeStateR() -> boxed;
auto applicativeStateL() -> boxed;

} // end namespace Data_Traversable_Accum_Internal

#endif // Data_Traversable_Accum_Internal_H

