// Generated by pscpp compiler

#ifndef Control_MonadPlus_H
#define Control_MonadPlus_H

#include "purescript.h"

namespace Control_MonadPlus {

using namespace purescript;

auto MonadPlus() -> const boxed&;
auto monadPlusArray() -> boxed;

} // end namespace Control_MonadPlus

#endif // Control_MonadPlus_H

