// Generated by pscpp compiler

#ifndef Data_FoldableWithIndex_H
#define Data_FoldableWithIndex_H

#include "purescript.h"

namespace Data_FoldableWithIndex {

using namespace purescript;

auto Tuple() -> const boxed&;
auto FoldableWithIndex() -> const boxed&;
auto foldrWithIndex() -> const boxed&;
auto traverseWithIndex_() -> const boxed&;
auto forWithIndex_() -> const boxed&;
auto foldrDefault() -> const boxed&;
auto foldlWithIndex() -> const boxed&;
auto foldlDefault() -> const boxed&;
auto foldableWithIndexMultiplicative() -> boxed;
auto foldableWithIndexMaybe() -> boxed;
auto foldableWithIndexLast() -> boxed;
auto foldableWithIndexFirst() -> boxed;
auto foldableWithIndexDual() -> boxed;
auto foldableWithIndexDisj() -> boxed;
auto foldableWithIndexConj() -> boxed;
auto foldableWithIndexAdditive() -> boxed;
auto foldWithIndexM() -> const boxed&;
auto foldMapWithIndexDefaultR() -> const boxed&;
auto foldableWithIndexArray() -> boxed;
auto foldMapWithIndexDefaultL() -> const boxed&;
auto foldMapWithIndex() -> const boxed&;
auto foldlWithIndexDefault() -> const boxed&;
auto foldrWithIndexDefault() -> const boxed&;
auto surroundMapWithIndex() -> const boxed&;
auto foldMapDefault() -> const boxed&;
auto findWithIndex() -> const boxed&;
auto anyWithIndex() -> const boxed&;
auto allWithIndex() -> const boxed&;

} // end namespace Data_FoldableWithIndex

#endif // Data_FoldableWithIndex_H

