// Generated by pscpp compiler

#ifndef Data_Bitraversable_H
#define Data_Bitraversable_H

#include "purescript.h"

namespace Data_Bitraversable {

using namespace purescript;

auto Bitraversable() -> const boxed&;
auto bitraverse() -> const boxed&;
auto lfor() -> const boxed&;
auto ltraverse() -> const boxed&;
auto rfor() -> const boxed&;
auto rtraverse() -> const boxed&;
auto bitraversableJoker() -> const boxed&;
auto bitraversableClown() -> const boxed&;
auto bisequenceDefault() -> const boxed&;
auto bisequence() -> const boxed&;
auto bitraversableFlip() -> const boxed&;
auto bitraversableProduct() -> const boxed&;
auto bitraversableWrap() -> const boxed&;
auto bitraverseDefault() -> const boxed&;
auto bifor() -> const boxed&;

} // end namespace Data_Bitraversable

#endif // Data_Bitraversable_H

