// Generated by pscpp compiler

#ifndef Control_Monad_Writer_Class_H
#define Control_Monad_Writer_Class_H

#include "purescript.h"

namespace Control_Monad_Writer_Class {

using namespace purescript;

auto MonadTell() -> const boxed&;
auto MonadWriter() -> const boxed&;
auto tell() -> const boxed&;
auto pass() -> const boxed&;
auto listen() -> const boxed&;
auto listens() -> const boxed&;
auto censor() -> const boxed&;

} // end namespace Control_Monad_Writer_Class

#endif // Control_Monad_Writer_Class_H

