// Generated by pscpp compiler

#ifndef Control_Monad_Gen_H
#define Control_Monad_Gen_H

#include "purescript.h"

namespace Control_Monad_Gen {

using namespace purescript;

auto Cons() -> const boxed&;
auto Nil() -> const boxed&;
auto FreqSemigroup() -> const boxed&;
auto AtIndex() -> const boxed&;
auto unfoldable() -> const boxed&;
auto semigroupFreqSemigroup() -> boxed;
auto semigroupAtIndex() -> boxed;
auto getFreqVal() -> const boxed&;
auto getAtIndex() -> const boxed&;
auto freqSemigroup() -> const boxed&;
auto frequency() -> const boxed&;
auto filtered() -> const boxed&;
auto suchThat() -> const boxed&;
auto choose() -> const boxed&;
auto atIndex() -> boxed;
auto fromIndex() -> const boxed&;
auto elements() -> const boxed&;
auto oneOf() -> const boxed&;

} // end namespace Control_Monad_Gen

#endif // Control_Monad_Gen_H

