// Generated by pscpp compiler

#ifndef Data_Monoid_Additive_H
#define Data_Monoid_Additive_H

#include "purescript.h"

namespace Data_Monoid_Additive {

using namespace purescript;

auto Additive() -> const boxed&;
auto showAdditive() -> const boxed&;
auto semigroupAdditive() -> const boxed&;
auto ordAdditive() -> const boxed&;
auto monoidAdditive() -> const boxed&;
auto functorAdditive() -> boxed;
auto eqAdditive() -> const boxed&;
auto eq1Additive() -> boxed;
auto ord1Additive() -> boxed;
auto boundedAdditive() -> const boxed&;
auto applyAdditive() -> boxed;
auto bindAdditive() -> boxed;
auto applicativeAdditive() -> boxed;
auto monadAdditive() -> boxed;

} // end namespace Data_Monoid_Additive

#endif // Data_Monoid_Additive_H

