// Generated by pscpp compiler

#ifndef Data_String_Regex_H
#define Data_String_Regex_H

#include "purescript.h"

namespace Data_String_Regex {

using namespace purescript;

auto showRegex() -> boxed;
auto search() -> boxed;
auto renderFlags() -> const boxed&;
auto regex() -> const boxed&;
auto parseFlags() -> const boxed&;
auto match() -> boxed;
auto flags() -> boxed;
auto showRegex_Prime_() -> const boxed&;
auto regex_Prime_() -> const boxed&;
auto source() -> const boxed&;
auto flags_Prime_() -> const boxed&;
auto test() -> const boxed&;
auto _match() -> const boxed&;
auto replace() -> const boxed&;
auto replace_Prime_() -> const boxed&;
auto _search() -> const boxed&;
auto split() -> const boxed&;

} // end namespace Data_String_Regex

#endif // Data_String_Regex_H

