// Generated by pscpp compiler

#ifndef Data_Void_H
#define Data_Void_H

#include "purescript.h"

namespace Data_Void {

using namespace purescript;

auto Void() -> const boxed&;
auto absurd() -> const boxed&;
auto showVoid() -> boxed;

} // end namespace Data_Void

#endif // Data_Void_H

