// Generated by pscpp compiler

#ifndef Data_Bifunctor_H
#define Data_Bifunctor_H

#include "purescript.h"

namespace Data_Bifunctor {

using namespace purescript;

auto Bifunctor() -> const boxed&;
auto bimap() -> const boxed&;
auto lmap() -> const boxed&;
auto rmap() -> const boxed&;

} // end namespace Data_Bifunctor

#endif // Data_Bifunctor_H

