// Generated by pscpp compiler

#ifndef Control_Comonad_Store_Trans_H
#define Control_Comonad_Store_Trans_H

#include "purescript.h"

namespace Control_Comonad_Store_Trans {

using namespace purescript;

auto StoreT() -> const boxed&;
auto runStoreT() -> const boxed&;
auto newtypeStoreT() -> boxed;
auto functorStoreT() -> const boxed&;
auto extendStoreT() -> const boxed&;
auto comonadTransStoreT() -> boxed;
auto comonadStoreT() -> const boxed&;

} // end namespace Control_Comonad_Store_Trans

#endif // Control_Comonad_Store_Trans_H

