// Generated by pscpp compiler

#ifndef Data_Array_Partial_H
#define Data_Array_Partial_H

#include "purescript.h"

namespace Data_Array_Partial {

using namespace purescript;

auto tail() -> const boxed&;
auto last() -> const boxed&;
auto init() -> const boxed&;
auto head() -> const boxed&;

} // end namespace Data_Array_Partial

#endif // Data_Array_Partial_H

