// Generated by pscpp compiler

#ifndef Data_Unit_H
#define Data_Unit_H

#include "purescript.h"

namespace Data_Unit {

using namespace purescript;

auto showUnit() -> boxed;
auto unit() -> const boxed&;

} // end namespace Data_Unit

#endif // Data_Unit_H

