// Generated by pscpp compiler

#ifndef Data_Semiring_H
#define Data_Semiring_H

#include "purescript.h"

namespace Data_Semiring {

using namespace purescript;

auto SemiringRecord() -> const boxed&;
auto Semiring() -> const boxed&;
auto zeroRecord() -> const boxed&;
auto zero() -> const boxed&;
auto semiringUnit() -> boxed;
auto semiringRecordNil() -> boxed;
auto semiringNumber() -> boxed;
auto semiringInt() -> boxed;
auto oneRecord() -> const boxed&;
auto one() -> const boxed&;
auto mulRecord() -> const boxed&;
auto mul() -> const boxed&;
auto addRecord() -> const boxed&;
auto semiringRecord() -> const boxed&;
auto add() -> const boxed&;
auto semiringFn() -> const boxed&;
auto semiringRecordCons() -> const boxed&;
auto intAdd() -> const boxed&;
auto intMul() -> const boxed&;
auto numAdd() -> const boxed&;
auto numMul() -> const boxed&;

} // end namespace Data_Semiring

#endif // Data_Semiring_H

