// Generated by pscpp compiler

#ifndef Data_String_CaseInsensitive_H
#define Data_String_CaseInsensitive_H

#include "purescript.h"

namespace Data_String_CaseInsensitive {

using namespace purescript;

auto CaseInsensitiveString() -> const boxed&;
auto showCaseInsensitiveString() -> boxed;
auto newtypeCaseInsensitiveString() -> boxed;
auto eqCaseInsensitiveString() -> boxed;
auto ordCaseInsensitiveString() -> boxed;

} // end namespace Data_String_CaseInsensitive

#endif // Data_String_CaseInsensitive_H

