// Generated by pscpp compiler

#ifndef Data_Monoid_Disj_H
#define Data_Monoid_Disj_H

#include "purescript.h"

namespace Data_Monoid_Disj {

using namespace purescript;

auto Disj() -> const boxed&;
auto showDisj() -> const boxed&;
auto semiringDisj() -> const boxed&;
auto semigroupDisj() -> const boxed&;
auto ordDisj() -> const boxed&;
auto monoidDisj() -> const boxed&;
auto functorDisj() -> boxed;
auto eqDisj() -> const boxed&;
auto eq1Disj() -> boxed;
auto ord1Disj() -> boxed;
auto boundedDisj() -> const boxed&;
auto applyDisj() -> boxed;
auto bindDisj() -> boxed;
auto applicativeDisj() -> boxed;
auto monadDisj() -> boxed;

} // end namespace Data_Monoid_Disj

#endif // Data_Monoid_Disj_H

