// Generated by pscpp compiler

#ifndef Control_Monad_Reader_H
#define Control_Monad_Reader_H

#include "purescript.h"

namespace Control_Monad_Reader {

using namespace purescript;

auto withReader() -> boxed;
auto runReader() -> const boxed&;
auto mapReader() -> const boxed&;

} // end namespace Control_Monad_Reader

#endif // Control_Monad_Reader_H

