// Generated by pscpp compiler

#ifndef Data_Semigroup_H
#define Data_Semigroup_H

#include "purescript.h"

namespace Data_Semigroup {

using namespace purescript;

auto Semigroup() -> const boxed&;
auto SemigroupRecord() -> const boxed&;
auto semigroupVoid() -> boxed;
auto semigroupUnit() -> boxed;
auto semigroupString() -> boxed;
auto semigroupRecordNil() -> boxed;
auto semigroupArray() -> boxed;
auto appendRecord() -> const boxed&;
auto semigroupRecord() -> const boxed&;
auto append() -> const boxed&;
auto semigroupFn() -> const boxed&;
auto semigroupRecordCons() -> const boxed&;
auto concatString() -> const boxed&;
auto concatArray() -> const boxed&;

} // end namespace Data_Semigroup

#endif // Data_Semigroup_H

