// Generated by pscpp compiler

#ifndef Data_Char_Gen_H
#define Data_Char_Gen_H

#include "purescript.h"

namespace Data_Char_Gen {

using namespace purescript;

auto genUnicodeChar() -> const boxed&;
auto genDigitChar() -> const boxed&;
auto genAsciiChar_Prime_() -> const boxed&;
auto genAsciiChar() -> const boxed&;
auto genAlphaUppercase() -> const boxed&;
auto genAlphaLowercase() -> const boxed&;
auto genAlpha() -> const boxed&;

} // end namespace Data_Char_Gen

#endif // Data_Char_Gen_H

