// Generated by pscpp compiler

#ifndef Control_Plus_H
#define Control_Plus_H

#include "purescript.h"

namespace Control_Plus {

using namespace purescript;

auto Plus() -> const boxed&;
auto plusArray() -> boxed;
auto empty() -> const boxed&;

} // end namespace Control_Plus

#endif // Control_Plus_H

