// Generated by pscpp compiler

#ifndef Data_EuclideanRing_H
#define Data_EuclideanRing_H

#include "purescript.h"

namespace Data_EuclideanRing {

using namespace purescript;

auto EuclideanRing() -> const boxed&;
auto mod() -> const boxed&;
auto gcd() -> const boxed&;
auto euclideanRingNumber() -> boxed;
auto euclideanRingInt() -> boxed;
auto div() -> const boxed&;
auto lcm() -> const boxed&;
auto degree() -> const boxed&;
auto intDegree() -> const boxed&;
auto intDiv() -> const boxed&;
auto intMod() -> const boxed&;
auto numDiv() -> const boxed&;

} // end namespace Data_EuclideanRing

#endif // Data_EuclideanRing_H

