// Generated by pscpp compiler

#ifndef Data_String_NonEmpty_CaseInsensitive_H
#define Data_String_NonEmpty_CaseInsensitive_H

#include "purescript.h"

namespace Data_String_NonEmpty_CaseInsensitive {

using namespace purescript;

auto CaseInsensitiveNonEmptyString() -> const boxed&;
auto showCaseInsensitiveNonEmptyString() -> boxed;
auto newtypeCaseInsensitiveNonEmptyString() -> boxed;
auto eqCaseInsensitiveNonEmptyString() -> boxed;
auto ordCaseInsensitiveNonEmptyString() -> boxed;

} // end namespace Data_String_NonEmpty_CaseInsensitive

#endif // Data_String_NonEmpty_CaseInsensitive_H

