// Generated by pscpp compiler

#ifndef Control_Alt_H
#define Control_Alt_H

#include "purescript.h"

namespace Control_Alt {

using namespace purescript;

auto Alt() -> const boxed&;
auto altArray() -> boxed;
auto alt() -> const boxed&;

} // end namespace Control_Alt

#endif // Control_Alt_H

